### ISSUE TITLE
[Module] ZeroDelayTouch

### ISSUE THREAD

**Issue by PietroVN-dev** [Magisk-Modules-Alt-Repo/submission#10]
**Name**: ZeroDelayTouch
**Description**:  ZeroDelayTouch is a module that focuses on improving the touch of the phone, trying to remove any type of delay.
**Link**: https://github.com/PietroVN-dev/ZeroDelayTouch

**Comment by Atrate** [comment]
Approved. Find your repo at: https://github.com/Magisk-Modules-Alt-Repo/ZeroDelayTouch.

You have been invited to collaborate within that repo. 

You'll have full Admin access over your module on this repo, including the permission to delete it entirely. Enjoy!

P.S.: Make sure to archive your repo on your personal account and use the Alt-Repo as your main repo. That way there are no discrepancies between versions. Enjoy!
