### ISSUE TITLE
[Module] GMS Doze (Block Find My Device)

### ISSUE THREAD

**Issue by CrazyBytesVE** [Magisk-Modules-Alt-Repo/submission#100]
**Name**: GMS Doze
**Description**:  GMS Doze, bassed Gloeyisk GMS Universal Module with some changes.
**Link**: https://github.com/CrazyBytesVE/GMS-Doze-BlockFindMyDevice

**Comment by HuskyDG** [comment]
Please atleast include English Readme

**Comment by CrazyBytesVE** [comment]
> Please atleast include English Readme

Mi idioma nativo es el español.

**Comment by FUENT3S** [comment]
Me podrías ayudar porfa, tengo un poco x3 pro con crdroid 8.7 la última versión, magisk 25.2, instaló tu modulo, reinicio y todo bien, pero cuando abro termux para verificar que este funcionando, colocó el comando y me dice que los servicios de google no están optimizados, (soy venezolano por si no se notó en la forma de escribir)

**Comment by HuskyDG** [comment]
Please use about module id

**Comment by CrazyBytesVE** [comment]
> 

Why?

**Comment by HuskyDG** [comment]
> > 
> 
> Why?

Because it is same as https://github.com/Magisk-Modules-Alt-Repo/GMS-Doze

**Comment by CrazyBytesVE** [comment]
> > > 
> > 
> > 
> > Why?
> 
> Because its id is same as https://github.com/Magisk-Modules-Alt-Repo/GMSDoze

https://github.com/CrazyBytesVE/GMS-Doze-BlockFindMyDevice This is correct repository.

**Comment by HuskyDG** [comment]
Approved, https://github.com/Magisk-Modules-Alt-Repo/GMSDozeBlockFind
