### ISSUE TITLE
[Module] 36DPI NavBar

### ISSUE THREAD

**Issue by CrazyBytesVE** [Magisk-Modules-Alt-Repo/submission#101]
**Name**: 36DPI NavBar
**Description**: Reduces the size of the navigation bar to 36 DPI, maximizing the available screen space.
**Link**: https://github.com/CrazyBytesVE/36-DPI-NavBar-Mod

**Comment by Atrate** [comment]
English README, please. You can translate it with DeepL for example.

**Comment by CrazyBytesVE** [comment]
> English README, please. You can translate it with DeepL for example.

My native language is Spanish. Anyway I added English to the readme.

**Comment by HuskyDG** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/NavBar_Resize, enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
