### ISSUE TITLE
[Module] 36 DPI NavBar for Miui 10-11-12

### ISSUE THREAD

**Issue by CrazyBytesVE** [Magisk-Modules-Alt-Repo/submission#102]
**Name**: 36 DPI NavBar for Miui 10-11-12
**Description**:  Reduces the size of the navigation bar to 36 DPI, maximizing the available screen space.
**Link**: https://github.com/CrazyBytesVE/36DPI-NavBar-Mod-Miui-10-11-12

**Comment by Atrate** [comment]
English README, please. You can translate it with DeepL for example.

**Comment by CrazyBytesVE** [comment]
> English README, please. You can translate it with DeepL for example.

Mi idioma nativo es el español.

**Comment by HuskyDG** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/NavBar_Resize_Miui10-11-12 , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
