### ISSUE TITLE
[Module] 36 DPI NavBar

### ISSUE THREAD

**Issue by CrazyBytesVE** [Magisk-Modules-Alt-Repo/submission#103]
**Name**: 36 DPI NavBar
**Description**:  Reduce el tamaño de la barra de navegación a 36 DPI, maximizando el espacio en pantalla disponible
**Link**: https://github.com/CrazyBytesVE/36-DPI-NavBar-Mod

**Comment by HuskyDG** [comment]
Can you give description in English? Thanks

**Comment by Atrate** [comment]
Duplicate of #101

**Comment by CrazyBytesVE** [comment]
> Can you give description in English? Thanks

Reduces the size of the navigation bar to 36 DPI, maximizing the available screen real estate
Link: https://github.com/CrazyBytesVE/36-DPI-NavBar-Mod
