### ISSUE TITLE
[Module] Heimdall For Android NDK

### ISSUE THREAD

**Issue by JonesqPacMan** [Magisk-Modules-Alt-Repo/submission#104]
**Name**: Heimdall For Android NDK
**Description**:  Heimdall is a cross-platform open-source tool suite used to flash firmware (aka ROMs) onto Samsung mobile devices. Static binary build for Android multi architecture target builded by NDK.
**Link**: https://github.com/jonesqpacman/heimdall-ndk

**Comment by HuskyDG** [comment]
Can you use the latest template for module

**Comment by jonesqpacman** [comment]
can i use mmt extended template ?

**Comment by Atrate** [comment]
MMT Extended's fine

**Comment by jonesqpacman** [comment]
done

**Comment by HuskyDG** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/heimdall-ndk , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
