### ISSUE TITLE
[Module] UPX For Android NDK

### ISSUE THREAD

**Issue by JonesqPacMan** [Magisk-Modules-Alt-Repo/submission#105]
**Name**: UPX For Android NDK
**Description**: UPX is a portable, extendable, high-performance executable packer for several different executable formats. It achieves an excellent compression ratio and offers very fast decompression. Your executables suffer no memory overhead or other drawbacks for most of the formats supported, because of in-place decompression. Static binary build for Android multi architecture target builded by NDK.
**Link**: https://github.com/jonesqpacman/upx-ndk

**Comment by HuskyDG** [comment]
It's recommended to avoid using old template

**Comment by jonesqpacman** [comment]
can i use mmt extended template ?

**Comment by jonesqpacman** [comment]
can i use mmt extended template ?

**Comment by jonesqpacman** [comment]
done

**Comment by HuskyDG** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/aupx-ndk , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
