### ISSUE TITLE
[Module] Clash for Magisk

### ISSUE THREAD

**Issue by Kry9toN** [Magisk-Modules-Alt-Repo/submission#106]
**Name**: Clash for Magisk
**Description**:  Clash meta core with service scripts for Android.
**Link**: https://github.com/Kry9toN/Clash4Magisk

**Comment by Atrate** [comment]
Hey, can you include additional info about your module (such as what Clash is) in your README?

**Comment by Kry9toN** [comment]
Done, i have change my readme you can check now, Thanks😁

**Comment by HuskyDG** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/Clash4Magisk, enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
