### ISSUE TITLE
[Module] QDL For Android NDK

### ISSUE THREAD

**Issue by JonesqPacMan** [Magisk-Modules-Alt-Repo/submission#108]
**Name**: QDL For Android NDK
**Description**:  Qualcomm Download (QDL) is a tool to communicate with Qualcomm System On a Chip bootroms to install or execute code. As open source tool (for Linux) that implements the Qualcomm Sahara and Firehose protocols has been developed by Linaro, and can be used for program (or unbrick) MSM based devices. Static binary build for Android multi architecture target builded by NDK.
**Link**: https://github.com/jonesqpacman/qdl-ndk

**Comment by HuskyDG** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/JonesqPacMan , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
