### ISSUE TITLE
[Module] Quick Settings Modded

### ISSUE THREAD

**Issue by CrazyBytesVE** [Magisk-Modules-Alt-Repo/submission#112]
**Name**: Quick Settings Modded
**Description**:  Makes the Quick Settings look less rounded (more rectangular).
**Link**: https://github.com/CrazyBytesVE/QS-Modded

**Comment by Atrate** [comment]
Looks good, but please provide the source code for the APK files you use in your module.

**Comment by CrazyBytesVE** [comment]
> Looks good, but please provide the source code for the APK files you use in your module.
It's a mod from another module, whose credits are in the repository.

**Comment by CrazyBytesVE** [comment]
> Looks good, but please provide the source code for the APK files you use in your module.

The source code of the apks used is already uploaded.

**Comment by Atrate** [comment]
Well, the Apktool modification config to be exact along with modified resources. Looks good, but if you choose to include it right there in the repo files, you'll also need to make sure that when installing they get deleted as they're not functionally related to the module. You could alternatively provide the files as a link to a separate repo or in a Wiki. Same for your other module.

**Comment by CrazyBytesVE** [comment]
> ‎Bueno, la configuración de modificación de Apktool para ser exactos junto con los recursos modificados. Se ve bien, pero si elige incluirlo allí mismo en los archivos de repositorio, también deberá asegurarse de que al instalar se eliminen, ya que no están funcionalmente relacionados con el módulo. Alternativamente, puede proporcionar los archivos como un enlace a un repositorio separado o en un Wiki. Lo mismo para su otro módulo.‎

The ready-to-install ZIP file located in /releases does not include these files. I uploaded it to the repository because you require it, but in Magisk module they are not installed. In none of the modules.

**Comment by CrazyBytesVE** [comment]
> Well, the Apktool modification config to be exact along with modified resources. Looks good, but if you choose to include it right there in the repo files, you'll also need to make sure that when installing they get deleted as they're not functionally related to the module. You could alternatively provide the files as a link to a separate repo or in a Wiki. Same for your other module.

The ready-to-install ZIP file located in /releases does not include these files. I uploaded it to the repository because you require it, but in Magisk module they are not installed. In none of the modules.

**Comment by Atrate** [comment]
That's good and all but our repository builds ZIPs automatically from the repo's main branch, and makes it available in the JSON to download, so it doesn't use your `/releases`

**Comment by CrazyBytesVE** [comment]
> That's good and all but our repository builds ZIPs automatically from the repo's main branch, and makes it available in the JSON to download, so it doesn't use your `/releases`

Then I eliminated them. If it's a lot of complication, leave it like that. Anyway I did the module for my use but I wanted to share it, but if it is so much complication from you, it doesn't matter. It will also be available in my repository. I got you the source code, I got the finished module...

**Comment by Atrate** [comment]
You can also provide the source code in a separate, empty branch, which should be trivial to set up.

**Comment by HuskyDG** [comment]
@CrazyBytesVE Can you provide the modified files inside apk?

**Comment by CrazyBytesVE** [comment]
> @CrazyBytesVE ¿Puede proporcionarme los archivos modificados dentro de apk??

You can extract them from my Git. There is the apk there, you can decompile it.
