### ISSUE TITLE
[Module] Modded Night Light

### ISSUE THREAD

**Issue by CrazyBytesVE** [Magisk-Modules-Alt-Repo/submission#114]
**Name**: Modded Night Light
**Description**:  Module for lowering the yellow intensity of the Night Light mode.
**Link**: https://github.com/CrazyBytesVE/Luz-Nocturna

**Comment by HuskyDG** [comment]
Can this module works universal?

**Comment by CrazyBytesVE** [comment]
> ¿Puede este módulo funcionar para casi ROMs?

I specified the ROMs for which it can work. In theory it should be compatible with most AOSP ROMs. It is not compatible (although you can try) with Miui, OneUI, Oxigen, etc.

**Comment by HuskyDG** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/Luz-Nocturna_Modded  , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
