### ISSUE TITLE
[Module] Xperia 10 III Google Assistant key remapper

### ISSUE THREAD

**Issue by lufeidotcom** [Magisk-Modules-Alt-Repo/submission#115]
**Name**: Xperia 10 III Google Assistant button remapper
**Description**:  A simple module that remaps the Google Assistant button into a camera button
**Link**: https://github.com/lufeidotcom/Xperia-10-III-GA-Remapper

**Comment by Atrate** [comment]
Your repository will be created under the name `pdx213_assistant_camera_remap`, as that's your module ID. Is that okay? If not, please change the id to what you want your repo name to be like.

**Comment by lufeidotcom** [comment]
Yes, that name should be okay

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/pdx213_assistant_camera_remap , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
