### ISSUE TITLE
[Module] Android Pie 2-Button Gesture Navigation

### ISSUE THREAD

**Issue by zQueal** [Magisk-Modules-Alt-Repo/submission#116]
**Name**: Android Pie 2-Button Gesture Navigation
**Description**:  A simple module which enables the Android Pie 2 button system navigation in system navigation settings.
**Link**: https://forum.xda-developers.com/t/magisk-module-bring-back-android-pie-2-button-gesture-navigation.4002831/

~~Attached~~ (Github won't allow the attachment) is the module which is confirmed working on;

 * Pixel 6
 * Pixel 5a 5G
 * Pixel 4
 * Pixel 3a XL

Tested on android versions;

 * 13
 * 12
 * 11

**Comment by Atrate** [comment]
Your module needs to be a GitHub repository.

**Comment by zQueal** [comment]
I've created a repository with the zip contents, and added the original zip from the XDA thread as a release. Hope this is good enough.

https://github.com/zQueal/Pie2-ButtonNavigation

**Comment by Atrate** [comment]
Is the APK you provide taken from official sources/ripped from an OS? Could you provide info in the README as to the source of the APK file?

**Comment by zQueal** [comment]
From the original thread;

> This Magisk Module simply adds the 2-button navigation overlay __from the Pixel 3__. No changes are made to any system files or properties.

The original author seems to imply that they pulled the APK directly from the Pixel 3 ROM, which upon inspection doesn't seem to hold true;

```
Detailed information:
App Name: 2 Button Navigation Bar
Package: com.android.internal.systemui.navbar.twobutton
Version: 1.0 (1)
Minimal Android: 10.0 (Q)
Target Android: 10.0 (Q)
Maximal Android: 
Support: Android
OpenGL ES: 1.0
Textures: 
Screens: small,normal,large,xlarge
Supported CPU: 
Supported DPI: 160,any
File Size: 8 KB
MD5: 18815C2FD9820E6000F86CAB9303BF51
SHA-1: A6F25C459D67E03A7422F936948162EA461FF118
Signature SHA-256: 
Signature SHA-1: 
Signature MD5: 
Signature DN: 
Email: 
Developer (CN): 
Organization (O): 
Organizational unit (OU): 
Locality (L): 
Country (C): 
State/city (ST): 
App Permissions count: 0
App Permissions:

Features:
+ android.hardware.faketouch
# android.hardware.faketouch (default feature for all apps)
@ application: label='2 Button Navigation Bar' icon=''
```

...

```
Signature-Version: 1.0
Created-By: 1.0 (Android SignApk)
SHA-256-Digest-Manifest: heEGKOaVlVIXlio3XTclp2ShxU2Bo+88k/LDSTHfC3c=
X-Android-APK-Signed: 2, 3

Name: AndroidManifest.xml
SHA-256-Digest: MOOHpzY9xEkSYaOb8T7Fb04k8r1J/cOgx3xwOaYiEJ4=

Name: resources.arsc
SHA-256-Digest: iwAEsDkSmbCPXE9f+0ldNXTXJOkdWwojt+To2ROJXvw=
```

[VirusTotal](https://www.virustotal.com/gui/file/f465c3f12b1f4ac205635ed69e439b2df06472cd564c98c7971671534f23e344?nocache=1).

Not sure where to go from here. The closest thing I was able to find to an official release is [this](https://github.com/aosp-mirror/platform_frameworks_base/tree/master/packages/overlays/NavigationBarMode2ButtonOverlay) which is mirrored directly from Google, but there is no APK.

**Comment by Atrate** [comment]
Thanks for providing the detailed information. I just noticed — so you're not the original creator of the module? Unfortunately, we require that modules be submitted by their module author, so unless you make a fork and become the maintainer of that fork, we'd need @MishaalRahman to submit this.

You can become the maintainer of a fork of this module if and only if the licenses are compatible. @MishaalRahman has not specified a license as far as I can see, so it's All Rights Reserved, please ask them about releasing this under a FOSS license and we'll be all good.

**Comment by zQueal** [comment]
👍
