### ISSUE TITLE
[Module]DTSX Ultra ZTE A2020G Pro Magisk Module

### ISSUE THREAD

**Issue by freMea** [Magisk-Modules-Alt-Repo/submission#117]
**Name**: DTSX Ultra ZTE A2020G Pro Magisk Module
**Description**:  
- An equalizer ported from ZTE A2020G Pro (P855A01)
- Post process type soundfx
- Changing ro.build.product and ro.product.model, may breaks your platform apps and features functionality.
- Sources: [https://github.com/reiryuki/DTSX-Ultra-ZTE-A2020G-Pro-Magisk-Module/blob/main/module.prop](https://github.com/reiryuki/DTSX-Ultra-ZTE-A2020G-Pro-Magisk-Module/blob/main/module.prop)

**Requirements**
- Android 9 and up
- Magisk installed

**Link**: https://github.com/reiryuki/DTSX-Ultra-ZTE-A2020G-Pro-Magisk-Module

**Comment by Atrate** [comment]
> The issue author must be the owner of the module being submitted, or have permission from the owner.

@reiryuki Did @freMea contact you before submitting this here?

**Comment by reiryuki** [comment]
@Atrate No
