### ISSUE TITLE
[Module] CustomizedNavbar

### ISSUE THREAD

**Issue by PycmShoma** [Magisk-Modules-Alt-Repo/submission#118]
**Name**: CustomizedNavbar

**Description**:  Increasing the thickness and wide of the indicator, Change color to match the theme's accent color.
 You can choose which of the overlays to apply during installation
 Volume up (+) to change selection. Install or no.
 Volume down (-) to apply
- Colored Navbar Overlay change the color of the gesture indicator
- Wided Navbar Overlay change the width of the gesture indicator
- Thickned Navbar Overlay change the thickness of the gesture indicator
- 
**Requirements**: v1.0 for A10/11
v.3.1 for A12/12.1

**Link**: https://github.com/PycmShoma/CustomizedNavbar

**Comment by Atrate** [comment]
Citing from README:

> You must provide the source code for any executables or APK files included in your submission. If you absolutely need to compile your code, please provide reproducible build instructions. An exception can be made for modules that provide compiled packages/binaries from trusted sources such as recognized developers on the Play Store. In such a case, you cannot modify the provided APKs unless doing so does not infringe on the author's copyright and you must provide the source code/APKtool configuration for modifications performed, if any. 

>You can provide the source code in various ways, including, but not limited to:

>   - On the project's Wiki page
>   - As a separate repository
>   - On a separate, empty branch
>   - Directly in the main branch, with instructions in customize.sh that delete it during installation

**Comment by PycmShoma** [comment]
Done.
Added overlays as source code to the repo. 
Inside each package is a link to my fork of overlays.  There are already compiled files in the Magisk archive

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/CustomizedNavbar , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
