### ISSUE TITLE
[Module] Space saving Ahead-of-Time

### ISSUE THREAD

**Issue by ez-me** [Magisk-Modules-Alt-Repo/submission#119]
**Name**: Space saving Ahead-of-Time
**Description**:  Changes how Android's dex2oat compiles packages to save space, rather than focus on speed.
**Link**: https://github.com/ez-me/ezme-dex-space/

**Comment by ez-me** [comment]
I haven't really made detailed expetimentation with logs and the such. However, I haven't had an OOM event since using it.

The only times I get issues are when using termux and firefox (which run programs not handled by dex2oat)

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/ezme-dex-space , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
