### ISSUE TITLE
[Module] Universal GMS Doze

### ISSUE THREAD

**Issue by YouSummoner** [Magisk-Modules-Alt-Repo/submission#120]
Name: Universal GMS Doze 
Description:  Doze Google Services to optimize battery backup.
Link: https://github.com/gloeyisk/universal-gms-doze

**Comment by Atrate** [comment]
> The issue author must be the owner of the module being submitted, or have permission from the owner.
@YouSummoner did you contact @gloeyisk before submitting this?

**Comment by YouSummoner** [comment]
I've asked, awaiting response..., Please wait.
