### ISSUE TITLE
[Module] 1 controller

### ISSUE THREAD

**Issue by Lolbg83** [Magisk-Modules-Alt-Repo/submission#121]
**Name**: 1 controller
**Description**:  A module that lets you use various previously buggy/unsupported game controllers (DualShock 1,2,3,4 and dualsense, Xbox 360, one, one S, Xbox series x/s, and Nintendo switch pro controller (currently no joy con support) among others)
**Link**: https://github.com/Magisk-Modules-Repo/OneController

**Comment by Atrate** [comment]
Already in repo.
https://github.com/Magisk-Modules-Alt-Repo/OneController
