### ISSUE TITLE
[Module]Open WebView

### ISSUE THREAD

**Issue by F3FFO** [Magisk-Modules-Alt-Repo/submission#122]
**Name**: Open WebView
**Description**: Open Webview change your system webview.
**Link**: https://github.com/F3FFO/Open-Webview

**Comment by HuskyDG** [comment]
Can you provide the source of zipsigner binary?
And can you include zipsigner compiled for all architecture (arm, arm64, x86, x64)?

**Comment by F3FFO** [comment]
Oh, you're right I forgot to specify the origin of zipsigner: https://github.com/Magisk-Modules-Repo/zipsigner
Unfortunately I was unable to find a separately compiled version of zipsigner for the various architectures. You let me know if it's a problem!

**Comment by HuskyDG** [comment]
Approved! https://github.com/Magisk-Modules-Alt-Repo/open_webview
It's better to archive your current repo and move to work on this repo!
Thanks!
