### ISSUE TITLE
[Module] OnePlus 8 Series & 9R Camera Unlocker

### ISSUE THREAD

**Issue by nipunnarang** [Magisk-Modules-Alt-Repo/submission#125]
**Name**: OnePlus 8 Series & 9R Camera Unlocker
**Description**:  Unlocks features like 48MP RAW10 support, auxiliary lenses (in custom ROMs only), Zero Shutter Lag (ZSL), etc. on the OnePlus 8, 8 Pro, 8T, and 9R
**Link**: https://github.com/nipunnarang/oneplus-8series-9r-camera-unlocker

**Comment by HuskyDG** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/oneplus-8series-9r-camera-unlocker , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
