### ISSUE TITLE
[Module] OnePlus 9 & 9 Pro Camera Unlocker

### ISSUE THREAD

**Issue by nipunnarang** [Magisk-Modules-Alt-Repo/submission#126]
**Name**: OnePlus 9 & 9 Pro Camera Unlocker
**Description**:  Unlocks face detection on the OnePlus 9 and 9 Pro
**Link**: https://github.com/nipunnarang/oneplus-9-9pro-camera-unlocker

**Comment by HuskyDG** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/oneplus-9-9pro-camera-unlocker , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
