### ISSUE TITLE
[Module] Hide UserDebug, Test-Keys and LineageOS

### ISSUE THREAD

**Issue by ez-me** [Magisk-Modules-Alt-Repo/submission#127]
**Name**: Hide UserDebug, Test-Keys and LineageOS
**Description**:  Change some props and "remove" LineageOS ones.
**Link**: https://github.com/ez-me/ezme-nodebug

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/ezme-nodebug, enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
