### ISSUE TITLE
[Module] Raiden Tweaks

### ISSUE THREAD

**Issue by raidenkkj** [Magisk-Modules-Alt-Repo/submission#128]
**Name**: Raiden Tweaks™
**Description**:  A simple kernel tweaker with extra functions.
**Link**: http://www.github.com/raidenkkj/Raiden-Tweaks

**Comment by raidenkkj** [comment]
> 

Yea!

**Comment by raidenkkj** [comment]
> Are your app open source?
Yea!

**Comment by HuskyDG** [comment]
what's the source code of RaidenTweaks.apk ?

**Comment by raidenkkj** [comment]
> what's the source code of RaidenTweaks.apk ?

Take a look here, it's based on spectrum: https://github.com/frap129/spectrum

**Comment by HuskyDG** [comment]
Approved.

Sorry for long response.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/RTKS , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
