### ISSUE TITLE
[Module] Swap RAM

### ISSUE THREAD

**Issue by HuskyDG** [Magisk-Modules-Alt-Repo/submission#13]
**Name**: Magisk RAM Swapper
**Description**:  Expand RAM memory by converting a part of storage to Swap RAM.
**Link**: https://github.com/HuskyDG/Magisk_RAM_Swapper

**Comment by tytydraco** [comment]
Hey! I'm working on approving your module. I'm without a computer for the holidays. I'll approve your module as soon as possible and get you started.

**Comment by tytydraco** [comment]
Approved! Check your email for the invite link. Enjoy <3

**Comment by Atrate** [comment]
> Hey! I'm working on approving your module. I'm without a computer for the holidays. I'll approve your module as soon as possible and get you started.

@tytydraco Feel free to assign me to such issues if you're away for a while, I can deal with them usually in less than a day.
