### ISSUE TITLE
[Module] Systemless mksh.rc

### ISSUE THREAD

**Issue by DerGoogler** [Magisk-Modules-Alt-Repo/submission#136]
**ID**: mkshrc
**Name**: Systemless mksh.rc
**Description**: Systemlessly mksh.rc for better Terminal experience to turn your device into a workstation :)
**Link**: https://github.com/Googlers-Repo/mkshrc
**Source code**: None

**Comment by HuskyDG** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/mkshrc , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
