### ISSUE TITLE
[Module] F-Droid Privileged Extension

### ISSUE THREAD

**Issue by entr0pia** [Magisk-Modules-Alt-Repo/submission#137]
**ID**: Fdroid-Priv
**Name**: F-Droid Privileged Extension
**Description**:  Install F-Droid Privileged Extension systemlessly.
**Link**: https://github.com/entr0pia/Fdroid-Priv
**Source code**: None

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/Fdroid-Priv , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
