### ISSUE TITLE
[Module] Magisk Bootloop Saver

### ISSUE THREAD

**Issue by HuskyDG** [Magisk-Modules-Alt-Repo/submission#14]
**Name**: Magisk Bootloop Saver
**Description**:  Protect your system from bootloop caused by Magisk modules.
**Link**: https://github.com/HuskyDG/Magisk_BootloopSaver

**Comment by tytydraco** [comment]
Approved, go bonkers ;)

**Comment by HuskyDG** [comment]
Ok, thanks! ❤
