### ISSUE TITLE
[Module] CyberGlitch-2077 Oxygen OS 13 Boot & Shutdown Animation

### ISSUE THREAD

**Issue by sodasoba1** [Magisk-Modules-Alt-Repo/submission#140]
**ID**: GlitchedCyberBoot
**Name**: CyberGlitch-2077 Oxygen OS 13 Boot & Shutdown Animation
**Description**: OxygenOS 13 only. This boot animation is a modified glitch effect version of the cyberpunk 2077 animation from the op8t cyberpunk edition with a glitched & color matched shutdown logo animation added.
**Link**: https://github.com/sodasoba1/CyberPunk-2077-OOS13-Modded-Boot-and-Shutdown-Animation
**Source code**: None

**Comment by HuskyDG** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/sodasoba1  , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
