### ISSUE TITLE
[Module] Zeetaa-Tweaks

### ISSUE THREAD

**Issue by NotZeetaa** [Magisk-Modules-Alt-Repo/submission#15]
Name: ZeetaaTweaks
Description:  Simple Magisk module which changes some kernel parameteres to improve user experience
Link: https://github.com/NotZeetaa/Zeetaa-Tweaks

**Comment by tytydraco** [comment]
Done! Enjoy bro :)

**Comment by NotZeetaa** [comment]
> Done! Enjoy bro :)

Thank you bro :)
