### ISSUE TITLE
[Module] GCC Toolchain

### ISSUE THREAD

**Issue by DerGoogler** [Magisk-Modules-Alt-Repo/submission#152]
**ID**: gcc_on_android
**Name**: GCC Toolchain
**Description**:  GCC Toolchain is usable to build many things, such as native modules for Node.js
**Link**: https://github.com/Googlers-Repo/gcc
**Source code**: None

**Comment by Atrate** [comment]
I think you have a typo in your module ID

**Comment by DerGoogler** [comment]
Thank you! Haven't seen it. Fixed.

**Comment by Atrate** [comment]
Where do you take the binaries from? Do you compile them yourself for aarch64?

**Comment by Atrate** [comment]
@DerGoogler This issue will be closed in 1 month if there continues to be no response.
