### ISSUE TITLE
[Module] Monet-All

### ISSUE THREAD

**Issue by YangguangZhou** [Magisk-Modules-Alt-Repo/submission#153]
**ID**: Monet-All
**Name**: Monet-All
**Description**:  Monet color picking integrated Magisk module, you can choose whether to install the corresponding application color picking module through the volume keys.
**Link**: https://github.com/YangguangZhou/Monet-All
**Source code**: None

**Comment by Atrate** [comment]
Your module does not follow the Magisk Module format, you can't have the module zip in the repository files.

Please include an English README.

Please include information about the source code of the apps included.

**Comment by YangguangZhou** [comment]
> On some ROMs, you must have some declared permissions file in `/system/etc/permissions` if you install some apps as `priv-app`

What should I do

**Comment by YangguangZhou** [comment]
> Your module does not follow the Magisk Module format, you can't have the module zip in the repository files.
> 
> Please include an English README.
> 
> Please include information about the source code of the apps included.

I've added a [README-en.md](https://github.com/YangguangZhou/Monet-All/blob/main/README-en.md) and made changes to the module

**Comment by Atrate** [comment]
Not sure we should allow a bunch of unverified apps from a non-FOSS, third-party app store like coolapk, what do you think @HuskyDG ?

**Comment by YangguangZhou** [comment]
> Not sure we should allow a bunch of unverified apps from a non-FOSS, third-party app store like coolapk, what do you think @HuskyDG ?

coolapk is a popular exchange platform for digital enthusiasts in China, there should be no problem

**Comment by DerGoogler** [comment]
> Not sure we should allow a bunch of unverified apps from a non-FOSS, third-party app store like coolapk, what do you think @HuskyDG ?

The source code of the APKs should be provided. I wouldn't let access a closed source APK to my device
