### ISSUE TITLE
[Module] Turkish Ad Hosts

### ISSUE THREAD

**Issue by symbuzzer** [Magisk-Modules-Alt-Repo/submission#154]
**ID**: Turkish-Ad-Hosts
**Name**: Turkish-Ad-Hosts
**Description**:  Necessary hosts file to block tracking (and possibly advertising) networks in commonly used mobile applications (and possibly WEB pages) in Turkey...
**Link**: https://github.com/symbuzzer/Turkish-Ad-Hosts/tree/main/magisk
**Source code**: source code is scattered in different places:
> > - MODULE.ZIP on [Releases](https://github.com/symbuzzer/Turkish-Ad-Hosts/releases)
> > - SYSTEM/ETC/HOSTS on [root directory of repo](https://github.com/symbuzzer/Turkish-Ad-Hosts)
> > - UPDATE.JSON on [module folder of repo](https://github.com/symbuzzer/Turkish-Ad-Hosts/tree/main/magisk)
> > - MODULE.PROP is creating dynamically via a [Github Workflow](https://github.com/symbuzzer/Turkish-Ad-Hosts/blob/main/.github/workflows/auto-update-release.yml) (see 'Create "module.prop" file' section)
> > - ALL OTHER FILES are getting dynamically from [MMT-Extended](https://github.com/Zackptg5/MMT-Extended) via a [Github Workflow](https://github.com/symbuzzer/Turkish-Ad-Hosts/blob/main/.github/workflows/auto-update-release.yml) (see 'Downloading "Zackptg5/MMT-Extended" template files' section)

**Comment by Atrate** [comment]
You'll need to make a separate repo that follows the [magisk module format](https://topjohnwu.github.io/Magisk/guides.html) if we are to integrate it into MMAR.

**Comment by symbuzzer** [comment]
> You'll need to make a separate repo that follows the [magisk module format](https://topjohnwu.github.io/Magisk/guides.html) if we are to integrate it into MMAR.

I will when you integrate it into MMAR. But it will still need to get updates from my repo? Will it possible?

**Comment by Atrate** [comment]
No, all the module files need to be in the proper module format, with all files included for our build script to parse it correctly and for repo clients (like Fox's module manager) to download a proper archive.

**Comment by symbuzzer** [comment]
This is not possible. Because the hosts file, which is the heart of the module, is in my repo and the module is created automatically as this file is updated. Thank you for your attention, I also understand your security concerns. But at this stage, due to technical reasons, I do not seem to be able to have my module on your system. Please revive this issue as you move to a more open and inclusive model.

**Comment by ysfchn** [comment]
> This is not possible. Because the hosts file, which is the heart of the module, is in my repo and the module is created automatically as this file is updated.

I don't see why this is not possible, it should be technically possible. You can create another repo which follows the file structure of a Magisk module, then you can commit your "hosts" file automatically when your main repository gets pushed. As you already use GitHub Actions, you can git push to another repository which you have access.

**Comment by symbuzzer** [comment]
> > This is not possible. Because the hosts file, which is the heart of the module, is in my repo and the module is created automatically as this file is updated.
> 
> I don't see why this is not possible, it should be technically possible. You can create another repo which follows the file structure of a Magisk module, then you can commit your "hosts" file automatically when your main repository gets pushed. As you already use GitHub Actions, you can git push to another repository which you have access.

I have some concerns about security. I only need to be in control of the repo. If I can be the only authority on this issue, I might prefer to work in a separate repo.
