### ISSUE TITLE
[Module] Themed Project

### ISSUE THREAD

**Issue by Osanosa** [Magisk-Modules-Alt-Repo/submission#164]
**ID**: ThemedProject
**Name**: Themed Project
**Description**:  Theming overlays collection and a manager
**Link**: http://www.github.com/Osanosa/ThemedProject
**Source code**: present in repo

**Comment by Osanosa** [comment]
Is this okay to publish zip file as a release?

**Comment by Osanosa** [comment]
If structure is strictly needed, can I just upload all files to a new repo?

**Comment by Atrate** [comment]
Your module must be a valid Magisk/Zygisk module. See the [Developer Guide](https://topjohnwu.github.io/Magisk/guides.html) for more info.

**Comment by Osanosa** [comment]
Okay, is it fine now?

**Comment by Atrate** [comment]
I think the structure looks good. Where do you get the included APK files from?

**Comment by Osanosa** [comment]
github.com/Osanosa/themedmanager

[Osanosa - Chat @ Spike](https://spikenow.com/r/a/?ref=spike-organic-signature&_ts=1znphb)	[1znphb]

On March 17, 2023 at 17:13 GMT, Atrate ***@***.***> wrote:

I think the structure looks good. Where do you get the included APK files from?

**Comment by Atrate** [comment]
What about the source code of all included apps? See the following guideline:

> You must provide the source code for any executables or APK files included in your submission. If you absolutely need to compile your code, please provide reproducible build instructions. An exception can be made for modules that provide compiled packages/binaries from trusted sources such as recognized developers on the Play Store. In such a case, you cannot modify the provided APKs unless doing so does not infringe on the author's copyright and you must provide the source code/APKtool configuration for modifications performed, if any.

**Comment by Osanosa** [comment]
Repository I'm submitting originally contained sources and module was distributed via releases. Then you've pointed out to the incorrect structure, so I moved sources to GitHub.com/Osanosa/themedsources and unpacked module here. 

(I asked if it is possible to just upload module files to newly created repository of yours and you did not answered)

Anyway included apks are just resource overlays and does not contain any code. Some of them are repackaged open source apks, mainly from crd, bliss and spark, others are created by myself from scratch. Sources are available at above-mentioned repository of mine.

**Comment by Osanosa** [comment]
Sorry, that repository isn't published yet, I'll make it in an hour, but you can check previous commit

**Comment by Osanosa** [comment]
https://github.com/Osanosa/ThemedSource

**Comment by Osanosa** [comment]
I did it. Will module be visible right after? I'm planning to finish an update this weekend and would want to upload it before going public.

**Comment by Atrate** [comment]
Yes, it will be visible immediately. If you want, you can ping me when you're ready for me to create the repo for you.

**Comment by Atrate** [comment]
@Osanosa Are you ready to have the repo created here?

**Comment by Osanosa** [comment]
I'm working on an update. It takes way more effort than I initially anticipated. I'll let you know once I'll finish.

**Comment by Osanosa** [comment]
Ye I did it

**Comment by Osanosa** [comment]
You can publish it

**Comment by Osanosa** [comment]
🤨

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/ThemedProject , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.

**Comment by Osanosa** [comment]
I have a tiny issue — module is included into subfolder when downloading

**Comment by Atrate** [comment]
What exactly do you mean by that?

**Comment by Osanosa** [comment]
![image](https://user-images.githubusercontent.com/80209416/236651460-4407b221-87aa-4fe4-877d-405075b70cdd.png)

**Comment by Osanosa** [comment]
unzip error

**Comment by Atrate** [comment]
Have you tried installing it through Fox's Magisk Module Manager?

**Comment by Osanosa** [comment]
well yeah thats where the problem's coming from 
![image](https://user-images.githubusercontent.com/80209416/236651532-f58ae7ff-c5e6-476e-a571-e26d6b1fed07.png)

**Comment by Osanosa** [comment]
should i change git config or what

**Comment by Atrate** [comment]
> well yeah thats where the problem's coming from ![image](https://user-images.githubusercontent.com/80209416/236651532-f58ae7ff-c5e6-476e-a571-e26d6b1fed07.png)

Does this happen with any other module from Magisk Module Alt Repo (not Androidacy repo)?

**Comment by Osanosa** [comment]
seems that every module is being downloaded like that yet i can't confirm since installing don't work for me on 2.0.2
