### ISSUE TITLE
data_restore_Courier

### ISSUE THREAD

**Issue by ziandzivan** [Magisk-Modules-Alt-Repo/submission#165]
**ID**: data_restore_Courier
**Name**: Courier of data_restore script for MAGISK-TWRP
**Description**:  Courier of latest version data_restore script to folder /sdcard.
**Link**: https://github.com/ziandzivan/data_restore_Courier
**Source code**: https://github.com/ziandzivan/data_restore_Courier/releases/tag/v2.11

**Comment by ziandzivan** [comment]
> Oh https://github.com/ziandzivan/data_restore_Courier#features

Yes.
It is for updating Script ![data_restore](https://github.com/ziandzivan/data_restore).
thanks

**Comment by ziandzivan** [comment]
> But Why?
for automatic updating the script from Magisk.

There are two things:
- data backup, which is already in the repo: https://github.com/Magisk-Modules-Alt-Repo/data_backup
- data restore of created backup above: https://github.com/ziandzivan/data_restore
There is a "Courier" to deliver updated any new version of data restore to user as well via Magisk: https://github.com/ziandzivan/data_restore_Courier
because "actually the Script data_restore is not Magisk module." according the https://github.com/ziandzivan/data_restore_Courier#features
and https://github.com/ziandzivan/data_restore#introduction
the data_restore is only script that can be run or from TWRP or from Magisk module installer. One the same script - from two places.

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/data_restore_Courier , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.

**Comment by PycmShoma** [comment]
Unfortunately Ivan (ziandzivan) died
It happened on 07.19.2023
From oncology

**Comment by Atrate** [comment]
I had no idea, my condolences. I'll keep his modules in MMAR for as long as they work.

**Comment by PycmShoma** [comment]
Thank you.
We also found out too late.
Ivan was part of the 4PDA community. His relatives reported on the forum about the loss in early August
