### ISSUE TITLE
[Module] SUPL replacer

### ISSUE THREAD

**Issue by D3SOX** [Magisk-Modules-Alt-Repo/submission#166]
**ID**: supl-replacer
**Name**: SUPL replacer
**Description**:  Magisk module to replace the SUPL provider in gps.conf 
**Link**: https://github.com/D3SOX/magisk-supl-replacer
**Source code**: https://github.com/D3SOX/magisk-supl-replacer

I would rename the repo to just `supl-replacer` when it's under the organization.
I'm not the original creator of this module, but they seem to be inactive and I'm maintaining it for some time now.

**Comment by Atrate** [comment]
LGTM. Is there any particular reason why you keep an empty directory structure in https://github.com/D3SOX/magisk-supl-replacer/tree/master/system instead of just creating it in `post-fs-data.sh` with `mkdir`?

**Comment by D3SOX** [comment]
Also thought about changing that. That logic was from the previous author

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/supl-replacer , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.

**Comment by D3SOX** [comment]
Thanks. I guess I should change the references like update URLs to the new owner now

Btw, repo invitations are also shown in GitHub notifications for a while now and I've already watched the repo because I've enabled auto-watching in settings.
