### ISSUE TITLE
[Module]UbuntuFontVinaooo

### ISSUE THREAD

**Issue by vinaooo** [Magisk-Modules-Alt-Repo/submission#172]
**ID**: UbuntuFontVinaooo
**Name**: Ubuntu Font - by Vinaooo
**Description**:  A simple module that A simple Magisk Module to install Ubuntu Fonts on Android.
**Link**: https://github.com/vinaooo/Ubuntu-Font-Vinaooo

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/UbuntuFontVinaooo , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
