### ISSUE TITLE
Memory Background Frozen[Module]

### ISSUE THREAD

**Issue by LeanxModulostk** [Magisk-Modules-Alt-Repo/submission#174]
**ID**: MemBacFro
**Name**: Memory Background Frozen
**Description**:  This module will cause apps that have been in the background for a certain amount of time to be placed in a "deep standby" state where they are granted less memory in the background and are more restricted from accessing system resources (more than what it would do in the background normally).
**Link**: https://github.com/LeanxModulostk/MemoryBackgroundFrozen
**Source code**: None

**Comment by Atrate** [comment]
Hey there,

Can you provide a link to Android Developer Documentation (or some other documentation source) that explains the `persist.sys.memfreeze.enable` property in your README?

**Comment by Atrate** [comment]
@LeanxModulostk Waiting for a response. Will close this issue in 1 month if there is no response.

**Comment by Atrate** [comment]
So, snake oil?

**Comment by LeanxModulostk** [comment]
information obtained from chatgtp but if you want just reject it
