### ISSUE TITLE
[Module] MiShare

### ISSUE THREAD

**Issue by araafroyall** [Magisk-Modules-Alt-Repo/submission#176]
**ID**: MiShare
**Name**: MiShare v2.15.0
**Description**:  Allow you to use MiShare Systemlessly
**Link**: https://github.com/araafroyall/MiShareMagiskModule
**Source code**: None

**Comment by Atrate** [comment]
Invalid module format. Your module must be a valid Magisk/Zygisk module. See the [Developer Guide](https://topjohnwu.github.io/Magisk/guides.html) for more info.

**Comment by araafroyall** [comment]
No, you are wrong The module is Working fine. See Releases there is a zip of module.. you can recheck

**Comment by Atrate** [comment]
Your whole module needs to be in the repo, not as a zip file. See the [Developer Guide](https://topjohnwu.github.io/Magisk/guides.html) for more info.

**Comment by araafroyall** [comment]
Ok wait... I will post files by tomorrow.

**Comment by araafroyall** [comment]
> Your whole module needs to be in the repo, not as a zip file. See the [Developer Guide](https://topjohnwu.github.io/Magisk/guides.html) for more info.

Sorry for late. I have now uploaded files . please check

**Comment by Atrate** [comment]
Okay, the structure looks good. What is the source of the APK file provided with the module?

**Comment by araafroyall** [comment]
> Okay, the structure looks good. What is the source of the APK file provided with the module?

I got the apk from Telegram channel of MIUI apps.. This Mishare not available in most of redmi devices so i made this module to help others. 

It allow to transfer files upto 45MB/s

**Comment by araafroyall** [comment]
Are you there.  Now approve this module

**Comment by Atrate** [comment]
> I got the apk from Telegram channel of MIUI apps..

> **Source Code Guidelines**
> You must provide the source code for any executables or APK files included in your submission. If you absolutely need to compile your code, please provide reproducible build instructions. An exception can be made for modules that provide compiled packages/binaries from trusted sources such as recognized developers on the Play Store.

Yeah, a random APK file from a telegram channel won't cut it, not trustworthy enough.

**Comment by araafroyall** [comment]
It is not a random apk. Its from official channel. Ok as you wish. I submitted 2 modules till now but not even 1 is allowed , do you have personal problem with me?. Ok Delete this submission issue . i will never submit any module to you again .
