### ISSUE TITLE
[Module] AFWall Boot AntiLeak

### ISSUE THREAD

**Issue by gjf** [Magisk-Modules-Alt-Repo/submission#18]
**Name**: AFWall Boot AntiLeak
**Description**:  Normally AFWall applies iptables rules when started. It means if Internet access is enabled on boot it is possible to reach network overcoming AFWall rules BEFORE it starts. This module will prevent it blocking internet access on boot BEFORE AFWall started and applied.
**Link**: https://github.com/gjf/AFWall-Boot-AntiLeak

**Comment by Atrate** [comment]
Why is this necessary? AFWall itself includes such a feature that works with Magisk.

**Comment by gjf** [comment]
It was reported numerous times: a built-in feature does not work and fails to block during boot.

**Comment by Atrate** [comment]
Makes sense.  

@gjf I have created a repository for you, enjoy! https://github.com/Magisk-Modules-Alt-Repo/AFWall-Boot-AntiLeak

Steps you need to take:
1. Archive the current repository
2. Check your e-mail for an invite link to https://github.com/Magisk-Modules-Alt-Repo/AFWall-Boot-AntiLeak
3. Add a license that permits the distribution of your module freely (e.g. the GPLv3/GPLv2/MIT/BSD/PD licenses)
