### ISSUE TITLE
[Module] Redmi K40s fix camera error In EEA and Global ROM

### ISSUE THREAD

**Issue by godvmxi** [Magisk-Modules-Alt-Repo/submission#180]
**ID**: FixRedmiK40sCamera
**Name**: Fix Redmi K40s Camera Reservse and mirror issue
**Description**:  When flashing the EEA and Global version to Redmi K40 CN hardware, the front and back cameras will have some control issues, such as mirroring and open front camera failure in the face detecting app.
**Link**: https://github.com/godvmxi/magisk-module-fix-redmi-k40s-camera
**Source code**: Yes

**Comment by Atrate** [comment]
Where did you get the libraries in https://github.com/godvmxi/magisk-module-fix-redmi-k40s-camera/tree/master/system/vendor from (if just from the chinese OS images, please provide a link in the README)

**Comment by Atrate** [comment]
Closing due to no response. Feel free to reopen this or make another issue once you've responded.
