### ISSUE TITLE
[Module] xmlpak-RE

### ISSUE THREAD

**Issue by rushiranpise** [Magisk-Modules-Alt-Repo/submission#183]
**ID**: xmlpak-RE
**Name**: xmlpak-RE
**Description**:  This module enables you to download and install vendor apps from Google Play. Their compatibility is not guaranteed.

What vendors are supported?

HTC, OnePlus, Essential, Asus, Nokia/HMD Global, Nothing, Google , Motorola, BlackBerry, Nextbit, BQ, Sony, Samsung, Cyanogen, Razer, NVIDIA, Acer, Microsoft.
**Link**: https://github.com/rushiranpise/xmlpak-RE/releases
**Source code**: [Github](https://github.com/rushiranpise/xmlpak-RE)

**Comment by Atrate** [comment]
Do you use MMT extended for anything in your module? I haven't noticed it doing anything useful

**Comment by rushiranpise** [comment]
> Do you use MMT extended for anything in your module? I haven't noticed it doing anything useful

Yes, i haved added for future releases and compatibility.

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/xmlpak-RE , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
