### ISSUE TITLE
Wi-Fi Bonding NoLog [Qcom]

### ISSUE THREAD

**Issue by LeanxModulostk** [Magisk-Modules-Alt-Repo/submission#185]
**ID**: wifi-bonding
**Name**: Wi-Fi Bonding NoLog [Qcom]
**Description**:  This module doubles your bandwidth and enables low latency mode, reduces the number of standby wakeups, and disables Wi-Fi packet logging (has high overhead and various related security issues) to save battery life.
**Link**: https://github.com/LeanxModulostk/wifi-bonding-nolog
**Source code**: none

**Comment by Atrate** [comment]
Your repository has no module files in it.

**Comment by LeanxModulostk** [comment]
I already uploaded the files, I forgot 😅

**Comment by LeanxModulostk** [comment]
I just updated the module :)

**Comment by Atrate** [comment]
@HuskyDG could you take a look at this module as well? I am kind of put off by the snake-oil-like sounding claims but I don't have enough time to dig deep for now.

![image](https://github.com/Magisk-Modules-Alt-Repo/submission/assets/26827848/520511f4-cac2-4bac-8fb0-d7f78ce28014)

**Comment by Atrate** [comment]
Could you change your module ID to `wifi-bonding-nolog`, @LeanxModulostk ?

**Comment by LeanxModulostk** [comment]
done and update the file post-fs-data.sh

**Comment by Atrate** [comment]
One last question, similar to #191: Why do you sometimes use `resetprop` and sometimes `system.prop` and not one or the other?

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/wifi-bonding-nolog , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
