### ISSUE TITLE
[Module] Pixel Tensor Audio Decompressor

### ISSUE THREAD

**Issue by JoshuaDoes** [Magisk-Modules-Alt-Repo/submission#186]
**ID**: pixel-tensor-audio-decompressor
**Name**: Pixel Tensor Audio Decompressor
**Description**:  Patches mixer_paths.xml on Pixel Tensor devices to decompress the digital PCM volume. 
**Link**: https://github.com/JoshuaDoes/pixel-tensor-audio-decompressor/releases
**Source code**: https://github.com/JoshuaDoes/pixel-tensor-audio-decompressor

**Comment by Atrate** [comment]
The repository link you provide needs to be *just* the module, in such a way that downloading the zip of the repository would result in the ready-to-install module being downloaded.

**Comment by JoshuaDoes** [comment]
Could I alternatively create a secondary repository where that's the case? The main repository needs to stay the way it is tbh, for the sake of providing the video explanation of using the module (linked to in `README.md` and the XDA thread), as well as the build script to compile and inject updates to the text menu engine. Both would be considered bloat in the actual module releases.

And two side questions along with the reasons:
- I noticed in the recently approved "Disable high volume warning" module that their `update.json` disincludes the `zipUrl` and `changelog` values. What's the appropriate measure to be compatible with your backend's module updates?
- I recently had to break in-app Magisk update support due to a bug (or intended security precaution) where distributed binaries aren't permitted for execution in update-based ZIP downloads, and I had to modify my `CHANGELOG.md` to reflect on this change. Are you aware of whether or not AMM has this same issue? The included `menu` and `tinymix` binaries are executable when the module is installed via local storage, hence breaking in-app updates, but if this isn't a problem with AMM then I'm willing to restore a functional update and changelog solution to the alternative repository.

**Comment by Atrate** [comment]
> Could I alternatively create a secondary repository where that's the case?

Yes, that's not a problem.

> I noticed in the recently approved "Disable high volume warning" module that their update.json disincludes the zipUrl and changelog values. What's the appropriate measure to be compatible with your backend's module updates?

Our repo does not rely on `update.json`, instead it uses a very similar method to the old magisk module repo - it creates a zip directly from the main branch for each new commit.

> I recently had to break in-app Magisk update support due to a bug (or intended security precaution) where distributed binaries aren't permitted for execution in update-based ZIP downloads, and I had to modify my CHANGELOG.md to reflect on this change. Are you aware of whether or not AMM has this same issue? The included menu and tinymix binaries are executable when the module is installed via local storage, hence breaking in-app updates, but if this isn't a problem with AMM then I'm willing to restore a functional update and changelog solution to the alternative repository.

I don't think this would be a problem with MMAR but I can't say that with 100% certainty

**Comment by JoshuaDoes** [comment]
[Here's the alternative repository](https://github.com/JoshuaDoes/pixel-tensor-audio-decompressor-module)!

I'll investigate other alt-repo repositories to see if there's anything else I can try doing with it later on.
And if it turns out that AMM suffers from the same issue with executing extracted binaries, I'll have to look into refactoring the module to be a shell of itself and make it download everything necessary from each update first, including adding self-update support to the finalized module install. But that's only if it's necessary! I'll do testing as soon as it's approved and imported.

**Comment by Atrate** [comment]
LGTM but I'd recommend adding a readme for more information in the module manager.

**Comment by JoshuaDoes** [comment]
> LGTM but I'd recommend adding a readme for more information in the module manager.

Will do as soon as I get around to finishing update v2.2.0! Been quite busy so may be slightly longer

**Comment by Atrate** [comment]
Alright. In the meantime, I've gotten around to creating the repo.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/pixel-tensor-audio-decompressor , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
