### ISSUE TITLE
[Module] Fluent Emoji

### ISSUE THREAD

**Issue by k3rnelpanik** [Magisk-Modules-Alt-Repo/submission#189]
**ID**: FluentEmojiMagisk
**Name**: Fluent Emoji (Microsoft)
**Description**:  Replaces system emojis with Fluent Emojis from Microsoft with the magic of Magisk
**Link**: https://www.github.com/k3rnelpanik/FluentEmojiMagisk
**Source code**: https://www.github.com/k3rnelpanik/FluentEmojiMagisk

**Comment by Atrate** [comment]
LGTM, though could you add a link to where you got `fluent.ttf` from? (Or clarify if it's a rip)

**Comment by k3rnelpanik** [comment]
> LGTM, though could you add a link to where you got `fluent.ttf` from? (Or clarify if it's a rip)

The current one is a rip, but i'm currently working on using Google's NotoEmoji project to build the ttf from Microsoft's emojis available in their repo.

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/FluentEmojiMagisk , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
