### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by Atrate** [Magisk-Modules-Alt-Repo/submission#19]
@tytydraco @Fox2Code I'd appreciate your input on this matter.

I hope this would never become relevant, but just as a precaution, should we add a **recommendation** about the preferred licensing of modules in the repo? By that I mean licenses that permit free distribution of code/binaries, such as the GPL/MIT/BSD/PD licenses.

If you agree, I can add that to the README.

**Comment by tytydraco** [comment]
Hey, great idea! I think a GPL license or any open source license should be recommended, but not required, since we are the freedom version of the official repo.
