### ISSUE TITLE
[Module] Mulch System WebView Overlay

### ISSUE THREAD

**Issue by LeanxModulostk** [Magisk-Modules-Alt-Repo/submission#190]
**ID**: mulch-system-webview
**Name**: Mulch System WebView Overlay
**Description**:  Enable the use of Mulch as the Systen (Webview with better security and privacy) [version 116.0.5845.78]
**Link**: https://github.com/LeanxModulostk/mulch-webview-overlay
**Source code**: None

**Comment by Atrate** [comment]
How does your module differ from https://github.com/A4Alpha/mulch-webview-overlay ?

**Comment by LeanxModulostk** [comment]
no need to install app separately

**Comment by Atrate** [comment]
If you can't have the APK in the github repo, it won't be packaged correctly, as the zip releases don't matter.
