### ISSUE TITLE
Small Battery [Module]

### ISSUE THREAD

**Issue by LeanxModulostk** [Magisk-Modules-Alt-Repo/submission#191]
**ID**: smallbattery
**Name**: Small Battery
**Description**:  This module makes the system think that it has a smaller battery than normal, which will apply more precise adjustments to save battery.
**Link**: https://github.com/LeanxModulostk/SmallBattery
**Source code**: None

**Comment by LeanxModulostk** [comment]
Because I noticed that some properties didn't change (persist) and I found this method

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/smallbattery , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
