### ISSUE TITLE
[Module] Cleaner Lite Pro

### ISSUE THREAD

**Issue by araafroyall** [Magisk-Modules-Alt-Repo/submission#195]
ID: cleaner-Lite-Pro
Name: Cleaner Lite Pro
Description: The Most Advance Cleaner Ever made for Android 
Link: https://github.com/araafroyall/cleaner-Lite-Pro
Source code: None

**Comment by Atrate** [comment]
From the README:
```
You must provide the source code for any executables or APK files included in your submission. If you absolutely need to compile your code, please provide reproducible build instructions. An exception can be made for modules that provide compiled packages/binaries from trusted sources such as recognized developers on the Play Store. In such a case, you cannot modify the provided APKs unless doing so does not infringe on the author's copyright and you must provide the source code/APKtool configuration for modifications performed, if any.
```

**Comment by araafroyall** [comment]
I made this app using SketchwarePro App from github . I am the developer of this apk (@araafroyall)

**Comment by Atrate** [comment]
I am aware you are the developer. 

From the README:

```
You must provide the source code for any executables or APK files included in
your submission
```

I do not see any source code in your module repo or your APK's "repo"

**Comment by araafroyall** [comment]
> I am aware you are the developer. 
> 
> From the README:
> 
> ```
> You must provide the source code for any executables or APK files included in
> your submission
> ```
> 
> I do not see any source code in your module repo or your APK's "repo"

The App is totally offline and userfreindly
and never collects any data .
i cant provide you complete source code as many people may make mod or crack version of this . hope you understand. 
The requires files i mentioned in repo

**Comment by araafroyall** [comment]
i have updated source codes . should i resubmit module request 🙂

**Comment by Atrate** [comment]
Yes, please resubmit. Your module repo needs to be separate from the source code repo, though, and the APKs.

**Comment by araafroyall** [comment]
ok i will do later by tomorrow

**Comment by araafroyall** [comment]
i have resubmit module , Now Check

**Comment by araafroyall** [comment]
> Yes, please resubmit. Your module repo needs to be separate from the source code repo, though, and the APKs.

Why are you not checking , i have submitted request yesterday

**Comment by BNX070** [comment]
> > Yes, please resubmit. Your module repo needs to be separate from the source code repo, though, and the APKs.
> 
> Why are you not checking , i have submitted request yesterday

Where is the source code repo?

**Comment by araafroyall** [comment]
> > > Yes, please resubmit. Your module repo needs to be separate from the source code repo, though, and the APKs.
> > 
> > 
> > Why are you not checking , i have submitted request yesterday
> 
> Where is the source code repo?

here is https://github.com/araafroyall/Cleaner-Pro-Lite
