### ISSUE TITLE
[Module] Better MIUI Icons

### ISSUE THREAD

**Issue by SpicyChair** [Magisk-Modules-Alt-Repo/submission#2]
**Name**: Better MIUI Icons
**Description**:  A module which adds the nice icons from MiRoom to any MIUI 12-based ROM, replacing the default icons.
**Link**: https://github.com/SpicyChair/Better-MIUI-Icons

**Comment by abursmh** [comment]
> Approved. Check your e-mail or [this page](https://github.com/SpicyChair/Better-MIUI-Icons/invitations), @SpicyChair. https://github.com/Magisk-Modules-Alt-Repo/Better-MIUI-Icons
