### ISSUE TITLE
[Module]

### ISSUE THREAD

**Issue by B0j4ngl35** [Magisk-Modules-Alt-Repo/submission#20]
**Name**: Disable RTT Mode
**Description**:  This is the way to turn off the real-time text (RTT) answer option for incoming and outgoing calls.

**Link**: https://github.com/B0j4ngl35/My-Modules

**Comment by Atrate** [comment]
Invalid submission format. Please follow the submission guidelines at: https://github.com/Magisk-Modules-Alt-Repo/submission/blob/master/README.md

Please also make the repository follows the format used in all Magisk Module repositories, see https://github.com/Magisk-Modules-Alt-Repo/Magisk-DRM-Disabler for a reference module.

If you want to add .zip files, you'll need to do it in the "releases" section of your repository (once we create one for you).
