### ISSUE TITLE
[Module] Cleaner Lite pro

### ISSUE THREAD

**Issue by araafroyall** [Magisk-Modules-Alt-Repo/submission#202]
**ID**: cleaner
**Name**: Cleaner Lite Pro
**Description**:  A Most Advance Cleaner For Android
**Link**: https://github.com/araafroyall/Cleaner-Lite-Pro
**Source code**: None

**Comment by araafroyall** [comment]
why no one is assisting for this ?

**Comment by Atrate** [comment]
1. chmod 777? Really?https://github.com/araafroyall/Cleaner-Lite-Pro/blob/878e8124e3e9eac1d586a320d8c012a5e00f1e52/customize.sh#L33C52-L33C56
2. No hard-coded paths https://github.com/araafroyall/Cleaner-Lite-Pro/blob/878e8124e3e9eac1d586a320d8c012a5e00f1e52/system/bin/cleanerlitepro#L18C5-L18C5
3. Why is this even a module? This just installs the app as a normal user would and nothing else.

**Comment by araafroyall** [comment]
1. This is module because i will add magisk module support in it , to perform clean by rm -rf method by placing script at system level. 

2. should i remove /system/bin

**Comment by Atrate** [comment]
> This is module because i will add magisk module support in it , to perform clean by rm -rf method by placing script at system level.

1. You can do that via just asking for root access in the app, no need to make it a module.

2. https://superuser.com/questions/1034079/is-it-safe-to-chmod-777-everything

**Comment by araafroyall** [comment]
just leave this shit explaination

I think you have a personal problem with me.
you idiots never allowing my any module. 
not this one , and not mishare module and 2+.
You stupids have any personal problem with me . 
i make source code just beacause of this module but you still rejected .
Just leave from here you Idiots 😡😡😡
