### ISSUE TITLE
[Module] Universal_System_App_Installer

### ISSUE THREAD

**Issue by hc841** [Magisk-Modules-Alt-Repo/submission#204]
### ID

universal_system_app_installer

### Name

Universal System App Installer

### Description

A Magisk module to install apks as system apps.

### Module repository link

https://github.com/hc841/Universal_System_App_Installer

**Comment by Atrate** [comment]
![image](https://github.com/Magisk-Modules-Alt-Repo/submission/assets/26827848/a7ab0bf3-b965-4ac2-8fa4-4d0632539c5d)

Based on the instructions you provided, it does not make much sense for this to be in a module repo, considering that people will need to download and repack it manually anyways.
