### ISSUE TITLE
[Module] Magisk Tailscaled

### ISSUE THREAD

**Issue by anasfanani** [Magisk-Modules-Alt-Repo/submission#209]
### ID

magisk-tailscaled

### Name

Magisk Tailscaled

### Description

Magisk module for running Tailscale on rooted Android devices.

### Module repository link

https://github.com/anasfanani/Magisk-Tailscaled

### Source code link (for compiled binaries/APKs)

https://github.com/tailscale/tailscale

**Comment by anasfanani** [comment]
Please let me know what I missed, I'am still learning github & coding, also is my license valid ?

**Comment by DerGoogler** [comment]
License looks good to me. 

customize.sh, [line 11](https://github.com/anasfanani/Magisk-Tailscaled/blob/08d837ce383407823df411d1ea21b5e561f1a258/customize.sh#L11); why is the adb dir hard coded?
customize.sh, [line 24-26](https://github.com/anasfanani/Magisk-Tailscaled/blob/main/customize.sh#L24-L26); unnecessary permission changes

I'm a new moderator, so @Atrate, or some other mod should overlook it

**Comment by anasfanani** [comment]
> License looks good to me.

Thankyou

> customize.sh, [line 11](https://github.com/anasfanani/Magisk-Tailscaled/blob/08d837ce383407823df411d1ea21b5e561f1a258/customize.sh#L11); why is the adb dir hard coded? 

Yeah I'm sorry this is my first time develop a magisk module, I copy from this example [line 147](https://github.com/ViRb3/magisk-frida/blob/master/base/install.sh#L147);  

I had to use `unzip` directly would call internal BusyBox applets.

> customize.sh, [line 24-26](https://github.com/anasfanani/Magisk-Tailscaled/blob/main/customize.sh#L24-L26); unnecessary permission changes

I will remove this line asap.

Thankyou for your review.

**Comment by anasfanani** [comment]
Hello, I've recently updated my `customize.sh` file in this commit: https://github.com/anasfanani/Magisk-Tailscaled/commit/6c86fd1eb5de062892af535ad7402cc3be44f157.

Remove unnecessary permission changes.

To ensure that the binary files `tailscale` and `tailscaled` are executable. To achieve this, I've set the permissions for these binaries using the `set_perm_recursive` function with `$F_TARGETDIR` as the target directory, which is set to `$MODPATH/system/bin`. 

Remove hard coded adb dir and use `unzip` directly.

And small typo fix for cleanup.

**Comment by DerGoogler** [comment]
To ensure that the binaries are executable:
```shell
set_perm $MODPATH/system/bin/tailscale 0 0 0755
set_perm $MODPATH/system/bin/tailscaled 0 0 0755
```

**Comment by anasfanani** [comment]
Apologize, why I should use two lines with hard coded binary name instead 1 line only should enough using `set_perm_recursive ` functions. ?

`set_perm_recursive <directory> <owner> <group> <dirpermission> <filepermission> [context]`

**Comment by DerGoogler** [comment]
> Apologize, why I should use two lines with hard coded binary name instead 1 line only should enough using `set_perm_recursive ` functions. ?
> 
> `set_perm_recursive <directory> <owner> <group> <dirpermission> <filepermission> [context]`
> 
> 
> 
> 

`$MODPATH/system/bin/tailscale` isn't hard coded.

**Comment by anasfanani** [comment]
https://github.com/anasfanani/Magisk-Tailscaled/commit/a82ea30ba126b684d373d295b93031f72515a6c4

**Comment by anasfanani** [comment]
No update ?

**Comment by DerGoogler** [comment]
Hey @anasfanani, I haven't forgotten your submission, I'm currently enjoying the holidays with my friends and family.

I'll be available tomorrow again. ✌️

**Comment by anasfanani** [comment]
I have improve my module also, https://github.com/anasfanani/Magisk-Tailscaled/tree/dev

**Comment by DerGoogler** [comment]
Approved 👍.

I've created you a repo at https://github.com/Magisk-Modules-Alt-Repo/Magisk-Tailscaled. Please check if you received an repo invite.

Enjoy it, @anasfanani

**Comment by anasfanani** [comment]
> Approved 👍.
> 
> I've created you a repo at https://github.com/Magisk-Modules-Alt-Repo/Magisk-Tailscaled. Please check if you received an repo invite.
> 
> Enjoy it, @anasfanani

Thankyou @DerGoogler

**Comment by anasfanani** [comment]
Hi @DerGoogler , can you assist me how to update the repo ?

**Comment by DerGoogler** [comment]
Hey @anasfanani,

I forgot to send you an invite back then. Please check your inbox if you have received an invite.

**Comment by anasfanani** [comment]
@DerGoogler Yea xD , I'm also confused why I cant manage my repo here, also for another repo please 
https://github.com/Magisk-Modules-Alt-Repo/magisk-autoboot

**Comment by DerGoogler** [comment]
Done
