### ISSUE TITLE
[Module] SQLite for arm, arm64, x86 and x64 devices

### ISSUE THREAD

**Issue by rojenzaman** [Magisk-Modules-Alt-Repo/submission#212]
### ID

sqlite3

### Name

SQLite for arm, arm64, x86 and x64 devices

### Description

This Magisk module provides a statically linked and stripped sqlite3 binary for arm64-v8a, armeabi-v7a, x86 and x86_64 devices.

### Module repository link

https://github.com/rojenzaman/sqlite3-magisk-module

**Comment by DerGoogler** [comment]
Missing source of the `sqlite3` binaries.

**Comment by DerGoogler** [comment]
Everything else looks good.

**Comment by rojenzaman** [comment]
I compile multi-arch SQLite binaries using this project: https://github.com/jacopotediosi/sqlite3-android

That project uses SQLite Amalgamation as a build source: https://sqlite.org/amalgamation.html

@DerGoogler Do you want me to keep the Makefile in my project with the [SQLite build scripts](https://github.com/jacopotediosi/sqlite3-android) separately in a parent project? Or is it enough just to mention the build scripts?

**Comment by rojenzaman** [comment]
If necessary I can create a build system like [MagiskSSH](https://gitlab.com/d4rcm4rc/MagiskSSH) that builds the magisk module and compiles SQLite binaries.

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/sqlite3 , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
