### ISSUE TITLE
[Module] custom-certificate-authorities

### ISSUE THREAD

**Issue by lelemka0** [Magisk-Modules-Alt-Repo/submission#213]
### ID

custom-certificate-authorities

### Name

Custom Certificate Authorities

### Description

Add custom CAs added to the setting and in specific directories as system CAs, while supporting older versions of Android and Android 14.
The module will automatically convert the certificate format to `PEM` using precompiled `openssl` binaries from termux repository.

### Module repository link

https://github.com/lelemka0/custom-certificate-authorities

### Source code link (for compiled binaries/APKs)

https://grimler.se/termux-packages-24/pool/main/o/openssl/

**Comment by DerGoogler** [comment]
Pre-complied Termux binaries requires Termux to be installed.

**Comment by lelemka0** [comment]
termux uses `deb` as the package format, which is the format used by the debian package manager. It can be manually extracted without termux.
Related Link: https://wiki.debian.org/deb

The extracted `openssl` binary is placed in `$MODDIR/openssl`.  If they should not be pre-placed in the module, they can also be downloaded and extracted from the termux repo at installation time.

**Comment by DerGoogler** [comment]
![image](https://github.com/Magisk-Modules-Alt-Repo/submission/assets/54764558/b197a7d0-e81e-42ae-b70e-d23825165eba)

1. What is `start.sh`?
2. You can't export `PATH` within a install script, it'll gone after a reboot. you'll need to do this over the `mkshrc` file
3. Missing binaries, `libssl.so.3` and `libcrypto.so.3`
4. Dosn't work without `LD_LIBRARY_PATH`

To make `openssl` fully available you'll need to modify the `/system/etc/mkshrc` file. To avoid conflict with other modules you should use Systemless Mkshrc as a requirement

Create a `system/etc/mkshrc.d/custom-certificate-authorities.d.sh` file with the contents

```shell
export PATH="$PATH:<opensll-location>"
export LD_LIBRARY_PATH="$LD_LIBRARY_PATH:<openssl-libs-location>"
```

or if you don't want Systemless Mkshrc as a requiement then can you place `openssl` in `/system/bin` and the libs inside `/system/libs`

**Comment by lelemka0** [comment]
> 1. What is `start.sh`?
> 2. You can't export `PATH` within a install script, it'll gone after a reboot. you'll need to do this over the mkshrc file

`start.sh` is not part of the installation process, but is used by `post-fs-data.sh`. It was created just for easier control of the logs, moving its contents to `post-fs-data` will still work fine.
https://github.com/lelemka0/custom-certificate-authorities/blob/6148d15d929544a21adf97a791acc37fdeec6a18/post-fs-data.sh#L15

> 3. Missing binaries, `libssl.so.3` and `libcrypto.so.3`

You can't unpack the `tar` under windows because some of the files are symbolic links, which is only available in linux.
```
/usr/lib/libssl.so -> ./libssl.so.3
/usr/lib/libcrypto.so -> ./libcrypto.so.3
```

> 4. Dosn't work without `LD_LIBRARY_PATH`

I exported PATH before using `openssl` in `start.sh`. The purpose of this module is not to add openssl to the system, so this is enough. 
https://github.com/lelemka0/custom-certificate-authorities/blob/6148d15d929544a21adf97a791acc37fdeec6a18/start.sh#L20

I did ignore `LD_LIBRARY_PATH` but `openssl` still works, I guess termux's `openssl-tool` is a static build, or `x509` doesn't need these libs. To avoid potential problems I would add it.

**Comment by DerGoogler** [comment]
Rejected.

https://github.com/Magisk-Modules-Alt-Repo/submission/issues/214#issuecomment-2154698308 (2)
