### ISSUE TITLE
[Module] custom-certificates 

### ISSUE THREAD

**Issue by YujiaCheng1996** [Magisk-Modules-Alt-Repo/submission#214]
### ID

custom-certificates

### Name

Custom Certificate

### Description

A Magisk module which adds custom certificate(s) to the system trust store.

### Module repository link

https://github.com/YujiaCheng1996/custom-certificates

### Source code link (for compiled binaries/APKs)

https://github.com/YujiaCheng1996/custom-certificates/module

**Comment by DerGoogler** [comment]
Hey @YujiaCheng1996,

thanks for your submission but your module doen't follow the Magisk Module Format. Please visit our [General Guidelines](https://github.com/Magisk-Modules-Alt-Repo/submission?tab=readme-ov-file#general-guidelines) and the [Magisk Module Format](https://topjohnwu.github.io/Magisk/guides.html#magisk-modules)

**Comment by YujiaCheng1996** [comment]
> Hey @YujiaCheng1996,
> 
> thanks for your submission but your module doen't follow the Magisk Module Format. Please visit our [General Guidelines](https://github.com/Magisk-Modules-Alt-Repo/submission?tab=readme-ov-file#general-guidelines) and the [Magisk Module Format](https://topjohnwu.github.io/Magisk/guides.html#magisk-modules)

fixed

**Comment by DerGoogler** [comment]
Rejected.

Reason is that this is a fork and automatically install certificates.
