### ISSUE TITLE
[Module] OffTombstoned

### ISSUE THREAD

**Issue by LeanxModulostk** [Magisk-Modules-Alt-Repo/submission#216]
### ID

OffTombstoned

### Name

Off Tombstoned

### Description

Tombstoned is the process responsible for generating system crash reports in the background.
![IMG_20240115_093405_065](https://github.com/Magisk-Modules-Alt-Repo/submission/assets/105339980/41d1c894-b6a0-46a8-b1a3-e69c02d2daf0)

### Module repository link

https://github.com/LeanxModulostk/Off-Tombstoned/

**Comment by Atrate** [comment]
https://github.com/LeanxModulostk/Off-Tombstoned/blob/7cc79076cd5a865c69ddcb61c67b9c26763e5883/customize.sh#L31

What exactly is that?

**Comment by Atrate** [comment]
@LeanxModulostk Waiting for an answer for 2 weeks and then closing this

**Comment by DerGoogler** [comment]
Rejected due no answer.
