### ISSUE TITLE
[Module] Bye Blur

### ISSUE THREAD

**Issue by LeanxModulostk** [Magisk-Modules-Alt-Repo/submission#217]
### ID

ByeBlur

### Name

Bye Blur

### Description

Disable the blur effect, this improves performance by discarding this complex visual effect.

### Module repository link

https://github.com/LeanxModulostk/Bye-Blur

**Comment by DerGoogler** [comment]
Available under: https://github.com/Magisk-Modules-Alt-Repo/Bye-Blur
