### ISSUE TITLE
[Module] CustomCACert

### ISSUE THREAD

**Issue by WindSpiritSR** [Magisk-Modules-Alt-Repo/submission#218]
### ID

customcacert

### Name

CustomCACert

### Description

Install custom CA certificate to the system store, support Android 14.

Easy to use, no need to use any other tools on your phone.

Full manual control over which certificates can be added as system certificates.

### Module repository link

https://github.com/WindSpiritSR/CustomCACert

**Comment by Atrate** [comment]
Your instructions only talk about zipping the module manually and then installing it - it would not make much sense to include in in the repo.

Alternatively, you can also say that a user can install the module from here and then add the cacerts to /data/adb/modules/customcacert/system/... and then reboot.

**Comment by Atrate** [comment]
Also, this is the third module that adds custom certs/CAs. Nothing in the rules against that, just mentioning it here.

https://github.com/Magisk-Modules-Alt-Repo/custom-certificate-authorities

https://github.com/Magisk-Modules-Alt-Repo/submission/issues/214

**Comment by Atrate** [comment]
@WindSpiritSR See https://github.com/Magisk-Modules-Alt-Repo/submission/issues/218#issuecomment-1902628692

Closing in 2 weeks if no answer is given.
