### ISSUE TITLE
[Module] USB Samplerate Unlocker

### ISSUE THREAD

**Issue by yzyhk904** [Magisk-Modules-Alt-Repo/submission#22]
**Name**: USB Samplerate Unlocker
**Description**:  This module unlocks the USB audio class (USB HAL) driver's limitation (up to 96kHz lock) to enjoy recent music streaming services which output greater than 96kHz high resolution sound.
**Link**: https://github.com/yzyhk904/usb-samplerate-unlocker

**Comment by Atrate** [comment]
Accepted.

@yzyhk904  I have created a repository for you, enjoy! https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker

Steps you need to take:

-    Archive the current repository
-    Check your e-mail for an invite link to https://github.com/Magisk-Modules-Alt-Repo/usb-samplerate-unlocker
