### ISSUE TITLE
[Module] Writable MicroSD

### ISSUE THREAD

**Issue by Kartatz** [Magisk-Modules-Alt-Repo/submission#224]
### ID

kaina

### Name

Writable MicroSD

### Description

Allow Android apps holding the WRITE_EXTERNAL_STORAGE permission to read and write on the MicroSD card.

### Module repository link

https://github.com/AmanoTeam/Kaina

**Comment by Atrate** [comment]
> Module ID must match repo name. In the event that this isn't the case, your new module repo's name will be the same as the module ID.

This means that your repo's name here on MMAR will be `kaina`, is that okay with you, @Kartatz ?

**Comment by Kartatz** [comment]
> This means that your repo's name here on MMAR will be kaina, is that okay with you, @Kartatz ?  

Yes, that's okay.

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/kaina , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
