### ISSUE TITLE
[Module] "pm Install" from anywhere

### ISSUE THREAD

**Issue by Kartatz** [Magisk-Modules-Alt-Repo/submission#225]
### ID

faina

### Name

"pm Install" from anywhere

### Description

Allow the `pm` CLI utility to install APKs from any location on your filesystem.

### Module repository link

https://github.com/AmanoTeam/Faina

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/faina , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
