### ISSUE TITLE
[Module] Android TCP Optimization

### ISSUE THREAD

**Issue by LeanxModulostk** [Magisk-Modules-Alt-Repo/submission#226]
### ID

ATCPO

### Name

Android TCP Optimization

### Description

Tuning the initcwnd and initrwnd parameters can have a significant improvement in TCP performance.

### Module repository link

https://github.com/LeanxModulostk/Android-TCP-Optimization

**Comment by DerGoogler** [comment]
Looks good @LeanxModulostk, but I recommend to use your file like this

```shell
#!/system/bin/sh
while [[ $(getprop sys.boot_completed) -ne 1 ]]; do
	sleep 1
done

# wait a while to ensure the system has started completely
sleep 20

#Optimización TCP de Android
ip route | while read p; do ip route change $p initcwnd 20 initrwnd 20; done

```

> And do not exit such scripts

**Comment by DerGoogler** [comment]
@LeanxModulostk, please answer within two weeks
