### ISSUE TITLE
[Module] eupif

### ISSUE THREAD

**Issue by nedorazrab0** [Magisk-Modules-Alt-Repo/submission#227]
### ID

eupif

### Name

euPIF

### Description

Provides pif.json by Xiaomi.eu for your mobile

### Module repository link

https://github.com/nedorazrab0/eupif

### Source code link (for compiled binaries/APKs)

https://github.com/curl/curl

**Comment by Atrate** [comment]
Your repository needs to follow the [magisk module format](https://topjohnwu.github.io/Magisk/guides.html) if we are to integrate it into MMAR.

**Comment by nedorazrab0** [comment]
fixed

**Comment by DerGoogler** [comment]
- `get_json.sh` has an hardcoded path: `/data/adb/pif.json`. do not hardcode paths
- not every device has the `curl` binary installed
- module seems to be vary useless

**Comment by nedorazrab0** [comment]
I added the [curl binaries](https://github.com/Zackptg5/Cross-Compiled-Binaries-Android/tree/master/curl/dynamic) to the module

**Comment by DerGoogler** [comment]
Sorry I cannot accept this "module", it only downloads a `pif.json` file on EVERY reboot which uses much performance or can lead to potential attacks.
