### ISSUE TITLE
[Module] Systemless Adblocker 

### ISSUE THREAD

**Issue by Burhanverse** [Magisk-Modules-Alt-Repo/submission#228]
### ID

systemless_adblocker 

### Name

Systemless Adblocker 

### Description

Ultimate adblocker module derived from gloeyisk/systemless-hosts

### Module repository link

https://github.com/Burhanverse/systemless-adblocker

**Comment by DerGoogler** [comment]
@Burhanverse, you'll have to include a `curl` binary to ensure that the installation works on all devices.

**Comment by Burhanverse** [comment]
@DerGoogler I have added the required binary to the module [check the commit here](https://github.com/Burhanverse/systemless-adblocker/commit/7899e872f1ab752b768e8895ffb9d8b499a8a3a7) and tested it on lmodroid 4.2 and it works fine. Thanks for pointing it out I haven't noticed it as the roms I tested in (MiUi 13, Crdroid 9.15, lmodroid 4.2 and risingos 3.0) already included `curl` by default.

**Comment by DerGoogler** [comment]
Approved 👍 

available at https://github.com/Magisk-Modules-Alt-Repo/systemless-adblocker and please check your inbox for an invite to your repo
