### ISSUE TITLE
[Module] Color Mode [DISPLAY_P3]

### ISSUE THREAD

**Issue by LeanxModulostk** [Magisk-Modules-Alt-Repo/submission#229]
### ID

ColorMode

### Name

Color Mode [DISPLAY_P3]

### Description

Cambia el modo de color de tu dispositivo a una gama más amplía [DISPLAY_P3] @modulostk
![IMG_20240521_153137_143](https://github.com/Magisk-Modules-Alt-Repo/submission/assets/105339980/f83e19e4-a995-4d8c-ac2a-c6cd90c48758)

### Module repository link

https://github.com/LeanxModulostk/DISPLAY_P3

**Comment by Atrate** [comment]
Please translate your submission and README into English.

**Comment by DerGoogler** [comment]
@LeanxModulostk, we're closing your submission in 2 weeks if no answer is given.

**Comment by DerGoogler** [comment]
Rejected due no answer.
