### ISSUE TITLE
[Module] audio-misc-settings

### ISSUE THREAD

**Issue by yzyhk904** [Magisk-Modules-Alt-Repo/submission#23]
**Name**: audio-misc-settings
**Description**:  A Magisk module for setting miscellaneous audio configuration values (media audio volume steps (100 steps), disabling the effects framework, raising resampling quality, etc.).
**Link**: https://github.com/yzyhk904/audio-misc-settings

**Comment by Atrate** [comment]
Accepted.

@yzyhk904 I have created a repository for you, enjoy! https://github.com/Magisk-Modules-Alt-Repo/audio-misc-settings

Steps you should take:

-    Archive the current repository
-    Check your e-mail for an invite link to https://github.com/Magisk-Modules-Alt-Repo/audio-misc-settings
