### ISSUE TITLE
[Module] StevenBlock

### ISSUE THREAD

**Issue by mikropsoft** [Magisk-Modules-Alt-Repo/submission#231]
### ID

StevenBlock

### Name

StevenBlock

### Description

Ad Blocking Module for Android (Magisk - KernelSU - APatch)

### Module repository link

https://github.com/mikropsoft/StevenBlock

**Comment by DerGoogler** [comment]
Hey @mikropsoft,

thanks for your submission, there is pne issue mentioned below.

### `install.sh` ([L-51-L53](https://github.com/mikropsoft/StevenBlock/blob/f53a97b6425e259a1cb36a8e8ed4ffc84dd31210/customize.sh#L51))

Please avoid giving binaries the permission of `777` instead give them `755`

**Comment by mikropsoft** [comment]
> Hey @mikropsoft,
> 
> thanks for your submission, there is pne issue mentioned below.
> 
> ### `install.sh` ([L-51-L53](https://github.com/mikropsoft/StevenBlock/blob/f53a97b6425e259a1cb36a8e8ed4ffc84dd31210/customize.sh#L51))
> Please avoid giving binaries the permission of `777` instead give them `755`

Sure, I'll test it and release an update in a few days, I'll let you know.

**Comment by mikropsoft** [comment]
@DerGoogler done.

**Comment by DerGoogler** [comment]
Approved.

Please check your inbox for an invitation
