### ISSUE TITLE
[Module] 80% Battery Charge Limit for Snapdragon-based Xiaomi/Redmi/POCO (a.k.a Night Charging)

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Alt-Repo/submission#233]
### ID

xiaomi-night-charging

### Name

80% Battery Charge Limit for Snapdragon-based Xiaomi/Redmi/POCO (a.k.a Night Charging)

### Description

By default, MIUI/HyperOS does not have the option in the settings (or anywhere in its UI) to limit battery charging, but it also ships with '/sys/class/qcom-battery/night_charging' file, which does that but, there's no way to turn it on out of the box. This is where this module comes in. 

### Module repository link

https://github.com/mge-hsl/xiaomi-night-charging

**Comment by DerGoogler** [comment]
Your account is to new for me. You'll have to find another mod that accepts your module.

**Comment by Atrate** [comment]
The module looks good, but @mge-hsl please specify a license for your module in the repository (as a LICENSE file and in the README). We recommend using a [Free-software license](https://en.wikipedia.org/wiki/Free-software_license), such as the [GNU AGPLv3](https://www.gnu.org/licenses/agpl-3.0.html).

**Comment by Atrate** [comment]
@mge-hsl Deadline: 2 weeks
