### ISSUE TITLE
[Module] Resampling for cheapies

### ISSUE THREAD

**Issue by yzyhk904** [Magisk-Modules-Alt-Repo/submission#234]
### ID

resampling-for-cheapies

### Name

Resampling for cheapies

### Description

Setting re-sampling parameters of AudioFlinger (the system-wide mixer) to improve audio quality of DAC's under $30 and LDAC BT devices especially.

### Module repository link

https://github.com/yzyhk904/resampling-for-cheapies

**Comment by DerGoogler** [comment]
Approved 👍

Please check your inbox for an invite, @yzyhk904.
