### ISSUE TITLE
[Module] Magisk-iOS-Emoji

### ISSUE THREAD

**Issue by hwittenborn** [Magisk-Modules-Alt-Repo/submission#235]
### ID

iOS_Emoji

### Name

Magisk-iOS-Emoji

### Description

Systemlessly replaces emoji font with iOS 17.4 Emoji

### Module repository link

https://github.com/Keinta15/Magisk-iOS-Emoji

**Comment by hwittenborn** [comment]
I'm not the repository owner, nor have I gotten permission to publish the package. I've [yet to receive a response](https://github.com/Keinta15/Magisk-iOS-Emoji/issues/38) from the owner in regards to publishing the package, though.

I would definitely prefer to have the project owner involved, but would there be any way to keep things going without them, at least until they're able to respond? I'm fine maintaining a fork of the upstream repository if that would help as well.

**Comment by DerGoogler** [comment]
We'll have to wait of the approval of the module owner.

I would say that the owner has 4 weeks time to give the go. If not, the owner has to submit the module themselves.

**Comment by Atrate** [comment]
> I'm fine maintaining a fork of the upstream repository if that would help as well.

That would work as well, but let's first wait for the original owner's response.

**Comment by Atrate** [comment]
Actually now that I think about it, it may be useful to mention @Keinta15 here...

**Comment by Atrate** [comment]
@hwittenborn Considering that the owner has not responded, feel free to make a fork of the repo and create another submission.
