### ISSUE TITLE
[Module] IRQ Balancer Configuration+

### ISSUE THREAD

**Issue by LeanxModulostk** [Magisk-Modules-Alt-Repo/submission#237]
### ID

irqbalance

### Name

IRQ Balancer Configuration+

### Description

This module modifies the msm_irqbalance.conf file and will set kgsl and msm_drm to different irqs to improve performance and latency.
![](https://i.ibb.co/kyK9jhg/1718764307752.png)

### Module repository link

https://github.com/LeanxModulostk/IRQ-Balancer-Configuration

**Comment by Atrate** [comment]
...
https://github.com/LeanxModulostk/IRQ-Balancer-Configuration/blob/main/system/vendor/etc/msm_irqbalance.conf

**Comment by DerGoogler** [comment]
> ... https://github.com/LeanxModulostk/IRQ-Balancer-Configuration/blob/2188e83c31585c0498dfb5fb631715796bf48e61/system/vendor/etc/msm_irqbalance.conf

wtf

**Comment by chickendrop89** [comment]
> ... https://github.com/LeanxModulostk/IRQ-Balancer-Configuration/blob/2188e83c31585c0498dfb5fb631715796bf48e61/system/vendor/etc/msm_irqbalance.conf

Huh? 😭😭😭
