### ISSUE TITLE
[Module] GPay-SQLite-Fix

### ISSUE THREAD

**Issue by stylemessiah** [Magisk-Modules-Alt-Repo/submission#24]
**Name**: GPay-SQLite-Fix
**Description**:  A simple Magisk module to provide the Google Pay SQL Fix as discovered by BostonDan, wrapped up to be automated by magisk and featuring changes/additions by other contributors.
**Link**: https://github.com/stylemessiah/GPay-SQLite-Fix

**Comment by Atrate** [comment]
Accepted.

@stylemessiah  I have created a repository for you, enjoy! https://github.com/Magisk-Modules-Alt-Repo/GPay-SQLite-Fix

Steps you should take:

-  Archive the current repository
-  Check your e-mail for an invite link to https://github.com/Magisk-Modules-Alt-Repo/GPay-SQLite-Fix
