### ISSUE TITLE
ultramusicpromax

### ISSUE THREAD

**Issue by BlackSky-1** [Magisk-Modules-Alt-Repo/submission#240]
### ID

ultramusicpromax

### Name

ULTRAMusicProMax

### Description

# ULTRAMusicProMax
Улучшение звука на устройствах Android поддержка 32bit/64bit

# Рекомендация:
•Ставьте Premium (All) версию если хотите максимальное качество звука но вы получите высокий разряд аккумулятора и нагрузка на процессор.
•Ставьте Pro версию высокое качество звука и средняя нагрузка на процессор.
•Если у вас BootLoop удалите внутри файл build.prop в версии:3.0.0.
•Удалите версию модуля 3.0.0 прежде ставить 4.0.0(исправлен Id).
### Module repository link

https://github.com/BlackSky-1/ULTRAMusicProMax

**Comment by DerGoogler** [comment]
- Module does not follow Magisk Module Format
- Missing english translation in the `RRADME.md`
- Module is not open source

Did you even read the guidelines?
