### ISSUE TITLE
geoXzram

### ISSUE THREAD

**Issue by Geovanne5** [Magisk-Modules-Alt-Repo/submission#242]
### ID

geoXzram

### Name

geoXzram

### Description

a simple module that changes the compression algorithm from zram to lz4 

### Module repository link

https://github.com/Geovanne5/geoXzram/tree/main

### Source code link (for compiled binaries/APKs)

https://github.com/Geovanne5/geoXzram/tree/main

**Comment by DerGoogler** [comment]
Invalid module repo format.
