### ISSUE TITLE
[Module] magisk-swapspace

### ISSUE THREAD

**Issue by chickendrop89** [Magisk-Modules-Alt-Repo/submission#243]
### ID

magisk-swpaspace

### Name

Magisk SwapSpace

### Description

An advanced module that allows for setting up swap space and related properties (swappiness, vfs-cache-pressure), on an android device

### Module repository link

https://github.com/chickendrop89/magisk-swapspace

**Comment by chickendrop89** [comment]
Bump

**Comment by chickendrop89** [comment]
Is this repo still alive?

**Comment by DerGoogler** [comment]
@chickendrop89 Yea, it is still alive. But admins also have a private life.

I'll try to review module tomorrow.

**Comment by chickendrop89** [comment]
> @chickendrop89 Yea, it is still alive. But admins also have a private life.
> 
> I'll try to review module tomorrow.

Okay, i understand. Take your time
