### ISSUE TITLE
[Module] img-flasher

### ISSUE THREAD

**Issue by YasserNull** [Magisk-Modules-Alt-Repo/submission#244]
### ID

img-flasher

### Name

Img Flasher

### Description

This module is versatile tool designed to simplify handling img files. The features of this tool include:

- Flashing like Fastboot: It allows you to flash files easily and quickly, saving time and effort in installation processes.
- Extracting files from the device: The tool provides the ability to extract img files directly from the device, making it easier to access the desired content.
- Unpack and Repack: It supports unpacking and repacking files, allowing modifications to the content as needed.

This tool is essential for developers and those interested in system modifications and handling img files with ease.

### Module repository link

https://github.com/YasserNull/img-flasher

### Source code link (for compiled binaries/APKs)

https://github.com/YasserNull/img-flasher

**Comment by DerGoogler** [comment]
Reasons for rejection:

1. Your module doesn't meet the Magisk Module Format.
2. You used Sketchware to build such app is very impressive (I used Sketchware Pro myself for years)
3. It looks like you can supply the whole module as app (In Sketchware Pro you can import libraries like `libsu` to enhance using shell command. You also can build custom blocks for it
4. Looks also like a tool for advanced users

The main reason is **1.**

Possible solutions:

- Make a separate for the module that follows the Magisk Module Format
- Ship the whole thing as single app (3.)
