### ISSUE TITLE
[Module] enable-blurs

### ISSUE THREAD

**Issue by HeyItsJono** [Magisk-Modules-Alt-Repo/submission#245]
### ID

enable-blurs

### Name

Enable Blurs

### Description

A module that enables support for enabling window-level blurs on a wide range of devices; changes some hidden props that other currently available modules do not, thus allowing it to work on more devices.

### Module repository link

https://github.com/HeyItsJono/enable-blurs

### Source code link (for compiled binaries/APKs)

https://github.com/HeyItsJono/enable-blurs/releases

**Comment by DerGoogler** [comment]
Your module might conflicts with https://github.com/Magisk-Modules-Alt-Repo/Bye-Blur.

Consider adding `common/repo.json`: https://github.com/DerGoogler/MMRL/wiki/repo.json#note

But looks good so far

@HeyItsJono
