### ISSUE TITLE
[Module] XtremeBS

### ISSUE THREAD

**Issue by DethByte64** [Magisk-Modules-Alt-Repo/submission#246]
### ID

XtremeBS

### Name

Xtreme Battery Saver

### Description

This module is a highly configurable battery saver for those who want to really stretch their battery lives from 100% to 0%

### Module repository link

https://github.com/DethByte64/Xtreme-Battery-Saver

### Source code link (for compiled binaries/APKs)

https://ftp.gnu.org/gnu/bash/

**Comment by DerGoogler** [comment]
- no permission are set for `bash`
- do not store `XtremeBS.conf` in `/sdcard` apps could access it

**Comment by DethByte64** [comment]
The requested changes have been made.

**Comment by DethByte64** [comment]
Love your work btw.
