### ISSUE TITLE
[Module] audio-samplerate-changer

### ISSUE THREAD

**Issue by yzyhk904** [Magisk-Modules-Alt-Repo/submission#247]
### ID

audio-samplerate-changer

### Name

Audio Samplerate Changer

### Description

A Magisk module for changing audio samplerates at the system-wide mixer for the best Hi-Fi experience

### Module repository link

https://github.com/yzyhk904/audio-samplerate-changer

**Comment by yzyhk904** [comment]
Is there any issue?

**Comment by ZG089** [comment]
> Is there any issue?

they are busy currently, but u may tag them, I mean u have been waiting for a whole month for submission💀

**Comment by DerGoogler** [comment]
`common/repo.json`:
```json
{
   "note": {
      "message": "\"DRC remover\" and \"USB Samplerate Unlocker\" are already included; Don't try installing them together"
   }
}
```
