### ISSUE TITLE
[Takedown] custom-certificate-authorities

### ISSUE THREAD

**Issue by Loukious** [Magisk-Modules-Alt-Repo/submission#249]
### ID

custom-certificate-authorities

### Name

Custom Certificate Authorities

### Module repository link

https://github.com/Magisk-Modules-Alt-Repo/custom-certificate-authorities

### Takedown Request Reason

Module is broken on A14+ and needs updating and the original developer's github account is deleted. I'd like you to delete it or transfer the ownership to me so I can keep it update. I already updated the module [here](https://github.com/Loukious/custom-certificate-authorities).

**Comment by DerGoogler** [comment]
I checked. The module has currently no maintainer. I would invite you as a new maintainer.

Try to keep credits to the original author.

**Comment by DerGoogler** [comment]
@Loukious
