### ISSUE TITLE
[Module]

### ISSUE THREAD

**Issue by stylemessiah** [Magisk-Modules-Alt-Repo/submission#25]
**Name**: SQLite3-Universal-Binaries
**Description**:  Universal (well almost, support from arm-v7+ ) SQLite3 binaries for Android. Initially created for use with Gpay SQLite Fix 
**Link**: https://github.com/stylemessiah/SQLite3-Universal-Binaries

**Comment by Atrate** [comment]
I have created a repository for you at: git@github.com:Magisk-Modules-Alt-Repo/SQLite3-Universal-Binaries.git , enjoy!

Steps we recommend you take now:

- Archive your current repository.
- Check your e-mail inbox for an invite to your new repository.
