### ISSUE TITLE
[Module] Re-Malwack

### ISSUE THREAD

**Issue by ZG089** [Magisk-Modules-Alt-Repo/submission#253]
### ID

Re-Malwack

### Name

Re-Malwack | Protection-maxxing 🛡️

### Description

Protect your Android device from ads, malware, and much more.  Just install Re-Malwack and you're safe. ✨
Supports all Android versions beginning with Android 7.0, and also protections are updated daily :) 👌

### Module repository link

https://github.com/ZG089/Re-Malwack

### Banner

https://ibb.co/k4JYt0q

### logo

https://ibb.co/MRfcZnF

**Comment by DerGoogler** [comment]
```
{
   "cover": "https://ibb.co/k4JYt0q",
   "icon": "https://ibb.co/MRfcZnF"
}
```

But I recommended GitHub Raw URLs

**Comment by DerGoogler** [comment]
`action.sh` will likey fail if the device has no `wget`

**Comment by ZG089** [comment]
> `common/repo.json`:
> 
> ```
> {
>    "cover": "https://ibb.co/k4JYt0q",
>    "icon": "https://ibb.co/MRfcZnF"
> }
> ```
> 
> But I recommended GitHub Raw URLs

oops i didn't know 

### Logo
https://raw.githubusercontent.com/ZG089/Re-Malwack/main/20240828-173916-0000-modified.png

### banner
https://raw.githubusercontent.com/ZG089/Re-Malwack/main/Add-Text-11-22-12-57-45.png





> `action.sh` will likey fail if the device has no `wget`.

hmm, ok I may use curl instead of wget.

@DerGoogler

**Comment by DerGoogler** [comment]
> > `common/repo.json`:
> > ```
> > {
> >    "cover": "https://ibb.co/k4JYt0q",
> >    "icon": "https://ibb.co/MRfcZnF"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > But I recommended GitHub Raw URLs
> 
> oops i didn't know
> 
> ### Logo
> https://raw.githubusercontent.com/ZG089/Re-Malwack/main/20240828-173916-0000-modified.png
> 
> ### banner
> https://raw.githubusercontent.com/ZG089/Re-Malwack/main/Add-Text-11-22-12-57-45.png
> 
> > `action.sh` will likey fail if the device has no `wget`.
> 
> hmm, ok I may use curl instead of wget.
> 
> @DerGoogler

@ZG089 you have to put `common/repo.json` into your root module folder so the repo can fetch this

**Comment by ZG089** [comment]
Oh, ok then.
Thanks for approving the module, sir :)
@DerGoogler

**Comment by ZG089** [comment]
ok, I added /common/repo.json successfully.
