### ISSUE TITLE
[Module] video-to-bootanimation

### ISSUE THREAD

**Issue by rhythmcache** [Magisk-Modules-Alt-Repo/submission#254]
### ID

video-to-bootanimation

### Name

Video To Bootanimation

### Description

set Videos as Bootanimation

### Module repository link

https://github.com/rhythmcache/video-to-bootanimation/

### Source code link (for compiled binaries/APKs)
1. /bin/zip - https://github.com/termux/termux-packages/tree/master/packages/zip  https://packages.termux.dev/apt/termux-main/pool/main/z/zip/

2. /bin/ffmpeg - https://github.com/Khang-NT/ffmpeg-binary-android

**Comment by DerGoogler** [comment]
Please provide the sources of the following binaries:
- https://github.com/rhythmcache/video-to-bootanimation/blob/main/bin/ffmpeg
- https://github.com/rhythmcache/video-to-bootanimation/blob/main/bin/zip

Remove comments: https://github.com/rhythmcache/video-to-bootanimation/blob/main/module.prop#L7

~What is that? 👉 https://github.com/rhythmcache/video-to-bootanimation/blob/main/customize.sh#L167
Just put `index.html` into the `webroot` folder...~

**Remove the `index.html`. Be serious developer.**

> [!CAUTION]
> I'm periodically checking module of their quality if something like this appears I'm immediately remove the access for **ALL** maintainers.

**Comment by rhythmcache** [comment]
1. **Sources of binaries:**
   - edited and added the sources link for the binaries 
     - FFmpeg - https://github.com/Khang-NT/ffmpeg-binary-android
     - ZIP - https://github.com/termux/termux-packages/tree/master/packages/zip  https://packages.termux.dev/apt/termux-main/pool/main/z/zip/

2. **Webroot and index.html:**
   - I’ve removed the `webroot` and `index.html` 

3. **Comments in `module.prop`:**
   - removed the comments from module.prop
