### ISSUE TITLE
[Module] wadbd

### ISSUE THREAD

**Issue by rhythmcache** [Magisk-Modules-Alt-Repo/submission#255]
### ID

wadbd

### Name

WirelessADBD-Controller

### Description

A simple Magisk module to control the Wireless ADB daemon

### Module repository link

https://github.com/rhythmcache/wireless-adb-controller

**Comment by DerGoogler** [comment]
But ignoring does not mean failing??

**Comment by rhythmcache** [comment]
> Why is the `wadbd` bin inside the install script? Please put the `wadbd` bin into `/system/bin`.

Fixed.
