### ISSUE TITLE
[Module] MagiskHideDenyRestore

### ISSUE THREAD

**Issue by stylemessiah** [Magisk-Modules-Alt-Repo/submission#27]
**Name**: MagiskHideDenyRestore
**Description**:  

Restores items to MagiskHide List or Deny List from /sdcard/MagiskList.txt

For the terminally lazy (like me), ive created a couple of simple magisk modules to backup and restore the packages and process you may have hidden via Magisk's MagiskHide (old magisk/custom) or Deny List (canary/alpha). In the old days, a trick (to essentially not have to retick all packages and process to hide - especially handy if you wanted to have the packages hidden before restoring your apps via something like Migrate, to make sure apps never had a chance to see root) was to simply backup /data/adb/magisk.db and restore it on ROM flashes. but with magisk.db schema changes this has now ceased to be a safe easy trick. So the way now (inspired by osm0sis from XDA) is to dump the list of packages and processes via the magiskhide ls (or magisk —deny ls) command to a text file and reimport it after a new ROM flash (assuming you have kept a copy off device if you do have to format data).

MagiskHideDenyBackup

    Backs up your magiskhide (or magisk deny) list to /sdcard/MagiskList.txt
    Writes a log file to /sdcard/MagiskHideDenyExport.log

MagiskHideDenyRestore

    Restores your magiskhide (or magisk deny) list from /sdcard/MagiskList.txt
    Writes a log file to /sdcard/MagiskHideImportExport.log

Both modules should detect which magisk variety youre using by listing the magisk applets and finding either magiskhide, or not...

**Link**: https://github.com/stylemessiah/MagiskHideDenyRestore

**Comment by Atrate** [comment]
I have created a repository for you at: git@github.com:Magisk-Modules-Alt-Repo/MagiskHideDenyRestore.git , enjoy!

Steps we recommend you take now:

- Archive your current repository.
- Check your e-mail inbox for an invite to your new repository.
