### ISSUE TITLE
[Module] custom-mkshrc-android

### ISSUE THREAD

**Issue by ghost** [Magisk-Modules-Alt-Repo/submission#271]
### ID

custom-mkshrc-android

### Name

Custom Mkshrc Android

### Description

allows you to load device default shell configuration from "/sdcard/.config/shrc"

### Module repository link

https://github.com/coldnw/custom-mkshrc-android

**Comment by DerGoogler** [comment]
There is no long thinking. Modules that are load files from `/sdcard/*` are not allowed due security reasons.
