### ISSUE TITLE
[Module] Systemless Debloater

### ISSUE THREAD

**Issue by zgfg** [Magisk-Modules-Alt-Repo/submission#28]
Systemless Debloater

Select and debloat preinstalled system apps. Supported up to SAR, Dynamic partitions and A12. Module must be installed through Magisk app, not TWRP - see OP instructions in the XDA thread:
https://forum.xda-developers.com/t/magisk-module-systemless-debloater-replace.4180083/

Github:
https://github.com/zgfg/SystemlessDebloater

Thanks

**Comment by Atrate** [comment]
I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/SystemlessDebloater, enjoy!

Steps we recommend you take now:

- Archive your current repository.
- Check your e-mail inbox for an invite to your new repository.
