### ISSUE TITLE
[Module] Lawnchair v12

### ISSUE THREAD

**Issue by Psk-Ita** [Magisk-Modules-Alt-Repo/submission#29]
**Name**: Lawnchair
**Description**: Launcher, Lawnicons, Feeds, Recents
**Link**: https://github.com/Psk-Ita/Lawnchair

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/Lawnchair, enjoy!

Check your e-mail inbox for an invite to your new repository.
