### ISSUE TITLE
[Module] micoG-Gapps

### ISSUE THREAD

**Issue by Psk-Ita** [Magisk-Modules-Alt-Repo/submission#30]
**Name**: microG-Gapps
**Description**:  alternative GApps based on microG
**Link**: https://github.com/Psk-Ita/microG-GApps

**Comment by Atrate** [comment]
I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/microG-GApps, enjoy!

Steps we recommend you take now:

- Archive your current repository.
- Check your e-mail inbox for an invite to your new repository.
