### ISSUE TITLE
[Module] Font-Evo-Sans

### ISSUE THREAD

**Issue by Psk-Ita** [Magisk-Modules-Alt-Repo/submission#31]
**Name**: Font-Evo-Sans
**Description**:  Evolve Evo font for AOSP rom
**Link**: https://github.com/Psk-Ita/Font-Evolve-Sans

**Comment by Atrate** [comment]
I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/Font-Evolve-Sans, enjoy!

Steps we recommend you take now:

    Archive your current repository.
    Check your e-mail inbox for an invite to your new repository.
