### ISSUE TITLE
[Module] OnePlus6Oxygen_22.J.62_debloater

### ISSUE THREAD

**Issue by Psk-Ita** [Magisk-Modules-Alt-Repo/submission#32]
**Name**: OnePlus6Oxygen_22.J.62_debloater
**Description**:  Enchilada's OxygenOS to AOSP vanilla (/e style)
**Link**: https://github.com/Psk-Ita/OnePlus6Oxygen_22.J.62_debloater

**Comment by Atrate** [comment]
As far as I can see, looking through your repository, you provide 2 zip files: a FULL and a LITE version of your module. You should combine them into one and let the user choose the version while flashing (or split it into two separate repositories).

You can let the user choose via the volume keys, see for example my implementation (based on Jman420's script): https://github.com/Magisk-Modules-Alt-Repo/Magisk-DRM-Disabler/blob/master/customize.sh

**Comment by Psk-Ita** [comment]
Ciao,
I'm going to close this issue, since I want to check what could be the solution I prefer
I have an additional question, how updates are managed on FoxMMM, I mean, one of my repo has already been approved, now I have a new version of it
what should I do to propagate update from my repo to the shared one?
Thanks

**Comment by Atrate** [comment]
You need to push to both repositories at once:

```
git remote set-url --add --push origin <address of original repo>
git remote set-url --add --push origin <address of MMAR repo>
```

**Comment by Psk-Ita** [comment]
yes, I got it,
I am keeping both aligned
thank you
