### ISSUE TITLE
[Module] Detach

### ISSUE THREAD

**Issue by xerta555** [Magisk-Modules-Alt-Repo/submission#33]
Name: Detach
Description: Detach any application from Play Store's updates
Link: [xerta555/Detach](https://github.com/xerta555/Detach)

**Comment by Atrate** [comment]
@tytydraco Are Mirror requests valid? Has anything changed since last rejections? If not, I'll remove the "mirror" issue template if that's the case.

**Comment by tytydraco** [comment]
> @tytydraco Are Mirror requests valid? Has anything changed since last rejections? If not, I'll remove the "mirror" issue template if that's the case.

I don't believe so, but I might be wrong. Are there any repos already on the alt repo that are being mirrored? I can't remember if we ever got it working.

**Comment by xerta555** [comment]
> @tytydraco Are Mirror requests valid? Has anything changed since last rejections? If not, I'll remove the "mirror" issue template if that's the case.

> > @tytydraco Are Mirror requests valid? Has anything changed since last rejections? If not, I'll remove the "mirror" issue template if that's the case.
> 
> I don't believe so, but I might be wrong. Are there any repos already on the alt repo that are being mirrored? I can't remember if we ever got it working.

There is a problem with my module?

**Comment by tytydraco** [comment]
Nope, just checking the method that we are going to add your module.

**Comment by Atrate** [comment]
> > @tytydraco Are Mirror requests valid? Has anything changed since last rejections? If not, I'll remove the "mirror" issue template if that's the case.
> 
> I don't believe so, but I might be wrong. Are there any repos already on the alt repo that are being mirrored? I can't remember if we ever got it working.

No, all the previous mirrors have been removed. If nothing changed since https://github.com/Magisk-Modules-Alt-Repo/submission/issues/8#issuecomment-687546369 , then mirroring is still unavailable.

**Comment by tytydraco** [comment]
> No, all the previous mirrors have been removed. If nothing changed since [#8 (comment)](https://github.com/Magisk-Modules-Alt-Repo/submission/issues/8#issuecomment-687546369) , then mirroring is still unavailable.

Got it. You're all good to remove the tag then. Thanks for confirming first.

**Comment by Atrate** [comment]
I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/Detach, enjoy!

Steps we recommend you take now:

- Archive your current repository.
- Check your e-mail inbox for an invite to your new repository.

**Comment by xerta555** [comment]
> I have created a repository for you at: Magisk-Modules-Alt-Repo/Detach, enjoy!

Nice!

> Archive your current repository.

I keep my repo

> Check your e-mail inbox for an invite to your new repository.

I have accepted the request.
