### ISSUE TITLE
[Module] Advanced Charging Controller (ACC)

### ISSUE THREAD

**Issue by VR-25** [Magisk-Modules-Alt-Repo/submission#34]
**Name**: Advanced Charging Controller

**Description**:  Mainly intended for extending battery service life on Android devices. In a nutshell, this is achieved through limiting charging current, temperature, and voltage. Any root solution is supported. Regardless of whether the system is rooted with Magisk, the installation is always "systemless".

**Link**: https://github.com/VR-25/acc/

**Comment by Atrate** [comment]
I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/acc/, enjoy!

Steps we recommend you take now:

- Check your e-mail inbox for an invite to your new repository.
