### ISSUE TITLE
[Module] fbind

### ISSUE THREAD

**Issue by VR-25** [Magisk-Modules-Alt-Repo/submission#35]
**Name**: fbind

**Description**: a versatile mounting utility for folders, disk images, LUKS/LUKS2 encrypted volumes, regular partitions and more.

**Link**: https://github.com/vr-25/fbind/

**Comment by Atrate** [comment]
I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/fbind, enjoy!

Steps we recommend you take now:

- Check your e-mail inbox for an invite to your new repository.
