### ISSUE TITLE
[Module] zRAM Swap Manager

### ISSUE THREAD

**Issue by VR-25** [Magisk-Modules-Alt-Repo/submission#36]
**Name**: zRAM Swap Manager

**Description**: a versatile zRAM swap manager with dynamic swappiness - for Android and GNU/Linux systems. 

**Link**: https://github.com/vr-25/zram-swap-manager/

**Comment by Atrate** [comment]
I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/zram-swap-manager, enjoy!

Steps we recommend you take now:

- Check your e-mail inbox for an invite to your new repository.
