### ISSUE TITLE
[Module] Daily Job Scheduler

### ISSUE THREAD

**Issue by VR-25** [Magisk-Modules-Alt-Repo/submission#37]
**Name**: Daily Job Scheduler

**Description**: runs commands and scripts on boot and at HH:MM. Any root solution is supported. Regardless of whether the system is rooted with Magisk, the installation is always "systemless".

**Link**: https://github.com/vr-25/djs

**Comment by Atrate** [comment]
I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/djs, enjoy!

Steps we recommend you take now:

    Check your e-mail inbox for an invite to your new repository.
