### ISSUE TITLE
[Module] microG Installer Revived

### ISSUE THREAD

**Issue by nift4** [Magisk-Modules-Alt-Repo/submission#38]
**Name**: microG Installer Revived
**Description**:  Install microG GmsCore, GsfProxy, FakeStore (or Play Store if you want so) and MapsV1 to /system/
**Link**: https://github.com/nift4/microg_installer_revived

**Comment by Atrate** [comment]
Hey there,

according to the submission guidelines, `Module ID must match repo name (otherwise Magisk Manager fails to download it).`. Do you want to change the module id to `microg_installer_revived` or should I just create a repository named `microg_installer` for you?

**Comment by nift4** [comment]
'microg_installer', I can't change the module id for backward compatibility reasons

**Comment by Atrate** [comment]
I have created a repository for you at: git@github.com:Magisk-Modules-Alt-Repo/microg_installer.git , enjoy!

Steps we recommend you take now:

- Check your e-mail inbox for an invite to your new repository.
