### ISSUE TITLE
[Module]s MARS_SOMs

### ISSUE THREAD

**Issue by Miustone** [Magisk-Modules-Alt-Repo/submission#39]
**Names**: 
0_MARS_SOM_CLEANER-GEAR_ZERO
1_MARS_SOM_BASE-GEAR_FIRST
2_MARS_SOM_OVERLAY-GEAR_SECOND
3_MARS_SOM_SYSTEM-GEAR_THIRD

**Description**:  
Adds Features, Functions and Improvements to Xperias on Stock Firmwares and GSIs and removes Bloat. Modular MMT-Extended ROM.

**Links**: 
https://github.com/Miustone/0_MARS_SOM_CLEANER-GEAR_ZERO
https://github.com/Miustone/1_MARS_SOM_BASE-GEAR_FIRST
https://github.com/Miustone/2_MARS_SOM_OVERLAY-GEAR_SECOND
https://github.com/Miustone/3_MARS_SOM_SYSTEM-GEAR_THIRD

**Comment by Atrate** [comment]
https://github.com/Miustone/3_MARS_SOM_SYSTEM-GEAR_THIRD has an invalid directory structure for Magisk Modules.

Is there any reason these can't be made into 1 module, where the user uses the volume keys to select which parts to install?

**Comment by Miustone** [comment]
Thanks for Your quick Response!
My main Reason was My slow Internet Connection. Part 0,1,2 are small sized and frequently Updated while Part/Gear 3 Contains Apps and Libs which only get updates from time to time. Volume Key Selection is already and only enabled on Part/Gear 0. 
Gear 1 Contains needed Props, Gear 2 Overlays and Gear 3 the main Content. They can also be used seperated but are depending on each other from 0 to 3. Means 3 needs all other Gears to work fully.

Bootloops and Issues/Bugs can also get easier detected on that way (debugging). I'm handling it like that for Months and the Users seem to like it. Hope it isn't an issue for the submission...

**Comment by Atrate** [comment]
I think it shouldn't be an issue, though I'd like @tytydraco to confirm.

**Comment by Miustone** [comment]
Thanks, i'll be Patient! 
Btw. also Thanks for this Repo, for Fox MMM and the Work behind it! I really love the Idea and the Community really needs this since the recent changes on Magisk itself... Hope i can get Part of it (:

**Comment by tytydraco** [comment]
> I think it shouldn't be an issue, though I'd like @tytydraco to confirm.

While it's a strange way to do it, it's technically not against any rules we have, so I'd say we can approve it. Your call.

**Comment by Atrate** [comment]
Approved. I have created the following repositories for you:

https://github.com/Magisk-Modules-Alt-Repo/0_MARS_SOM_CLEANER-GEAR_ZERO
https://github.com/Magisk-Modules-Alt-Repo/1_MARS_SOM_BASE-GEAR_FIRST
https://github.com/Magisk-Modules-Alt-Repo/2_MARS_SOM_OVERLAY-GEAR_SECOND
https://github.com/Magisk-Modules-Alt-Repo/3_MARS_SOM_SYSTEM-GEAR_THIRD

Check your e-mail for invitations to those repositories. Enjoy!
