### ISSUE TITLE
[Module] OnePlus6Oxygen_22.J.62_debloater

### ISSUE THREAD

**Issue by Psk-Ita** [Magisk-Modules-Alt-Repo/submission#40]
**Name**: OnePlus6Oxygen_22.J.62_debloater
**Description**:  OnePlus6Oxygen_22.J.62 (aka OOS 11.1.2.2) to pure AOSP build
**Link**: https://github.com/Psk-Ita/OnePlus6Oxygen_22.J.62_debloater

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: git@github.com:Magisk-Modules-Alt-Repo/OnePlus6Oxygen_22.J.62_debloater.git , enjoy!

Check your e-mail inbox for an invite to your new repository.

Please also check whether Fox Magisk Module Manager downloads your module correctly (as it has a lot of punctuation in the name)
