### ISSUE TITLE
[Module] SystemUI Bootloop Detection.

### ISSUE THREAD

**Issue by n3rd3x3** [Magisk-Modules-Alt-Repo/submission#41]
**Name**: SystemUI bootloop detection.
**Description**: Fixes SystemUI bootloops by detecting when SystemUI crashes (due to a Magisk module such as Substratum,) and reboots your device into safe mode automatically to disable Magisk so you can correct the faulty module.
**Link**: https://github.com/tsukimio/systemui-bootloop

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/systemui-bootloop, enjoy!

Check your e-mail inbox for an invite to your new repository.
