### ISSUE TITLE
[Module]  MiXplorer

### ISSUE THREAD

**Issue by Psk-Ita** [Magisk-Modules-Alt-Repo/submission#42]
**Name**: MiXplorer
**Description**: MiXplorer: An Android file explorer... and much more
**Link**: https://github.com/Psk-Ita/MiXplorer.git

**Comment by Atrate** [comment]
Could you please add a description as to what the module itself does (systemizing)? As well say *why* it's good to systemize the app.

**Comment by HuskyDG** [comment]
Systemize an app to priv-app, you must add whitelist permission to `/etc/permission` overwise you will end up of bootloop....
Also we can systemize an app easily by using Lucky Patcher....

![Screenshot_2022-02-05-17-47-28-483_ru jsziwumc rrvbnhgoc](https://user-images.githubusercontent.com/84650617/152642778-0be63d2b-a4aa-4807-862e-cd90e8190530.jpg)
![Screenshot_2022-02-05-17-48-14-817_lsr lsoatkbytje](https://user-images.githubusercontent.com/84650617/152642781-d34c2d5b-63ca-4462-9e5f-5ceb30cfabd9.jpg)

**Comment by Atrate** [comment]
@HuskyDG Don't worry, I know what systemizing means, I just want Psk-Ita to include a description of what the module does in README.md and say what benefits there are to systemizing MiXplorer instead of just installing it normally.

**Comment by Psk-Ita** [comment]
Ciao,
added some notes/description to the read.me file

**Comment by HuskyDG** [comment]
> Ciao, added some notes/description to the read.me file

Move to system priv-app, you must add whitlelist permissions in `/system/etc/permissions`, overwise it will be bootloop after reboot

**Comment by Atrate** [comment]
> Ciao, added some notes/description to the read.me file

Thanks. HuskyDG is also right, you should create permission files for the apks in `/system/etc/permissions`. From what I remember, not every single Android version requires that, but not doing that will cause bootloops in other cases.

**Comment by Atrate** [comment]
LGTM, we'll see if any edge case bootloops happen.

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/MiXplorer, enjoy!

Check your e-mail inbox for an invite to your new repository.

Make sure to change your repo push URLs in your local copy (or configure 2 parallel push URLs)."
