### ISSUE TITLE
[Module] CloudflareDNS4Magisk

### ISSUE THREAD

**Issue by xerta555** [Magisk-Modules-Alt-Repo/submission#43]
Name: CloudflareDNS4Magisk
Description:  Use CloudFlare DNS through Magisk.
Link: https://github.com/xerta555/CloudflareDNS4Magisk

**Comment by Atrate** [comment]
What is the reason for https://github.com/xerta555/CloudflareDNS4Magisk and https://github.com/xerta555/CloudflareDNS4Magisk-IPv6 to be separate modules?

**Comment by xerta555** [comment]
> What is the reason for [xerta555/CloudflareDNS4Magisk](https://github.com/xerta555/CloudflareDNS4Magisk) and [xerta555/CloudflareDNS4Magisk-IPv6](https://github.com/xerta555/CloudflareDNS4Magisk-IPv6) to be separate modules?

I couldn't find an easy way to check if the device had an IPv4 or v6 address at the time i made the module, so i split them into two.
If anyone has a time to do this via the `post-fs-data.sh` and/or `services.sh` files, i take :) .

**Comment by Atrate** [comment]
If a device had IPv6 functionality turned off, would trying to set the ipv6 DNS address cause any breakage?

**Comment by xerta555** [comment]
> If a device had IPv6 functionality turned off, would trying to set the ipv6 DNS address cause any breakage?

I honestly don't know and since i don't have a test device anymore, i don't feel like testing on my usual device.

**Comment by Atrate** [comment]
I think you should merge the two modules together and once someone tests it, it will be included in Magisk Module Alt Repo.

**Comment by xerta555** [comment]
> You should try merging the two modules together and once someone tests it, it will be included in Magisk Module Alt Repo.

Even if it could be detected, it can't be implemented anyway because it can't work that way.

I'll take an example so that we can understand:
A user with an Android device with Magisk installed and a SIM card granting internet access via IPv4. If for some reason the user's ISP decides to assign an IPv6 address without even notifying the user, then connectivity problems will occur until the user decides to remove the module or disable it.

Let's take another example:
A user with an Android device with Magisk installed and two SIM cards thus granting two internet accesses by means of two IP addresses (v4 or v6 or two identical types whatever), since the setting is applied at each startup statically and not dynamically before the startup of the network interfaces and the connection to the operator network, it is therefore not possible to change to design an adaptable universal module.

In any case for me, if we follow this logic it is not conceivable.
I had in mind to implement this when CloudFlare had set up their DNS service, all the other modules and methods were based on the same two logics: either by iptables command, or by declaring properties with the post-fs-data.sh file.

**Comment by Atrate** [comment]
Okay, this makes sense.

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/CloudflareDNS4Magisk, enjoy!

Check your e-mail inbox for an invite to your new repository.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.

**Comment by xerta555** [comment]
> Approved.
> 
> I have created a repository for you at: [Magisk-Modules-Alt-Repo/CloudflareDNS4Magisk](https://github.com/Magisk-Modules-Alt-Repo/CloudflareDNS4Magisk), enjoy!

Thanks for the module approval, that's cool.
 
> Check your e-mail inbox for an invite to your new repository.

Done.
>
> Make sure to change your local repository's push URLs or configure 2 parallel push URLs.

I think I'll keep a single update URL, easier to do, i'll do this tomorrow quietly it's getting late.
