### ISSUE TITLE
[Module] CloudflareDNS4Magisk-IPv6

### ISSUE THREAD

**Issue by xerta555** [Magisk-Modules-Alt-Repo/submission#44]
Name: CloudflareDNS4Magisk-IPv6
Description: Use CloudFlare DNS for IPv6 through Magisk.
Link: [xerta555/CloudflareDNS4Magisk](https://github.com/xerta555/CloudflareDNS4Magisk)](https://github.com/xerta555/CloudflareDNS4Magisk-IPv6)

**Comment by HuskyDG** [comment]
I think you should use `resetprop -n` instead of using `setprop` as it will cause deadlock problem

**Comment by HuskyDG** [comment]
I have open pull request

**Comment by xerta555** [comment]
> I think you should use `resetprop -n` instead of using `setprop` in [https://github.com/xerta555/CloudflareDNS4Magisk-IPv6/blob/master/common/post-fs-data.sh](https://github.com/xerta555/CloudflareDNS4Magisk-IPv6/blob/master/common/post-fs-data.sh?rgh-link-date=2022-02-05T12%3A37%3A42Z) as it will cause deadlock problem
> 
> Topjohnwu are already said here [topjohnwu.github.io/Magisk/guides.html#boot-scripts](https://topjohnwu.github.io/Magisk/guides.html#boot-scripts)

I have fix that, thanks for your help.

**Comment by Atrate** [comment]
Your module id needs to be different from the module id of the IPv4 module. It should be the same as the name of the repo, so `CloudflareDNS4Magisk-IPv6`

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/CloudflareDNS4Magisk-IPv6, enjoy!

Check your e-mail inbox for an invite to your new repository.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
