### ISSUE TITLE
[Module] Android 12 Extensions

### ISSUE THREAD

**Issue by ThePrimalPea** [Magisk-Modules-Alt-Repo/submission#45]
**Name**: Android 12 Extensions
**Description**: Enable and customize hidden features on Android 12.
**Link**: https://github.com/kdrag0n/android12-extensions

**Comment by Atrate** [comment]
@kdrag0n

**Comment by ThePrimalPea** [comment]
> @ThePrimalPea have you consulted with @kdrag0n (the module author) before submitting this issue?

Hmm, nope. Ok, i'll ask him now

**Comment by Atrate** [comment]
If kdrag0n wishes this module to be submitted, they need to do it themselves, in a new issue.
