### ISSUE TITLE
[Module] TTF Twemoji

### ISSUE THREAD

**Issue by ez-me** [Magisk-Modules-Alt-Repo/submission#46]
**Name**: TTF Twemoji
**Description**: This module changes Google Noto Emoji to Twitter Emoji.
**Link**: https://github.com/ez-me/ttf-twemoji

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/ttf-twemoji, enjoy!

Check your e-mail inbox for an invite to your new repository.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
