### ISSUE TITLE
[Module] Fullscreen/Immersive Gestures

### ISSUE THREAD

**Issue by DanGLES3** [Magisk-Modules-Alt-Repo/submission#47]
**Name**: Fullscreen/Immersive Gesture Tweaks for Android 10-12
**Description**:  This Magisk Module lets you tweak Android 10-12's gestures.
**Link**: https://github.com/DanGLES3/HideNavBar

Would like to have my module here as well since the official Magisk repository is no longer maintained

**Comment by Atrate** [comment]
I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/HideNavBar, enjoy!

Check your e-mail inbox for an invite to your new repository.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
