### ISSUE TITLE
[Module] BraviaEngine

### ISSUE THREAD

**Issue by enggarsulistyo** [Magisk-Modules-Alt-Repo/submission#50]
Name: BraviaEngine
Description: Sony Bravia Engine X-Reality
Link: https://github.com/enggarsulistyo/BraviaEngine

**Comment by Atrate** [comment]
A few issues:

1. Module ID must match repo name (otherwise Magisk Manager fails to download it).
2. The install script file should be named `customize.sh`, not `costumize.sh`

**Comment by enggarsulistyo** [comment]
Done fixed

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: git@github.com:Magisk-Modules-Alt-Repo/BraviaEngine.git , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
