### ISSUE TITLE
Fox MMM integration

### ISSUE THREAD

**Issue by Psk-Ita** [Magisk-Modules-Alt-Repo/submission#51]
Ciao,
this Is not a module submission, but just a suggestion
using the new "Fox MMM" app, I am seeing "download" button Is linked to repo source - so It Is not directly flashable
It shod be preferibile to download the flashable zip, what do you think?

**Comment by Atrate** [comment]
You should probably open/check open issues in this repo instead: https://github.com/Fox2Code/FoxMagiskModuleManager
