### ISSUE TITLE
[Module] BuiltIn-BusyBox

### ISSUE THREAD

**Issue by zgfg** [Magisk-Modules-Alt-Repo/submission#52]
**Name**: BuiltIn-BusyBox

**Description**:  Systemless BusyBox installing by the Magisk built-in busybox binary

**Link**: https://github.com/zgfg/BuiltIn-BusyBox

![BB-module](https://user-images.githubusercontent.com/51943147/153777083-5f8e0b83-e791-4f3b-94e8-1a7133b459ef.jpg)

![BB-Checker](https://user-images.githubusercontent.com/51943147/153777096-a4129d84-6677-45dc-a768-eabe9b470767.jpg)

**Comment by Atrate** [comment]
That's a really creative approach, honestly. What's the reason for the BB copying logic being in `post-fs-data.sh` instead of in `customize.sh`?

**Comment by zgfg** [comment]
> That's a really creative approach, honestly. What's the reason for the BB copying logic being in `post-fs-data.sh` instead of in `customize.sh`?

--install -s cretes symlinks, if executed in customize.sh (at the time of installation the module), they will not survive upon reboots

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/zgfg/BuiltIn-BusyBox, enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
