### ISSUE TITLE
[Module] Plex "Skip Intro" DPad Controller Fix

### ISSUE THREAD

**Issue by ohmybahgosh** [Magisk-Modules-Alt-Repo/submission#53]
**Name**: Plex "Skip Intro" DPad Controller Fix

**Description**:  Magisk module that maps key code 28 to "DPAD_ENTER" instead of "ENTER".  This allows for the DPad "OK" button to work properly, so that when you press the "OK" button, it actually presses the "Skip Intro" button.  This fixes a very annoying, and long ignored issue encountered when using a DPad controller inside PLEX on Android TV.  Without this module, when you press the "OK" button on a DPad Controller when the "Skip Intro" button appears in plex, it'll bring up player controls instead of actually skipping the intro.

**Link**: http://www.github.com/ohmybahgosh/PLEX_SKIP_INTRO_DPAD_CONTROLLER_FIX

![Plex "Skip Intro" DPad Controller Fix Banner Logo](https://i.imgur.com/yV96iAv.png)

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/PLEX_SKIP_INTRO_DPAD_CONTROLLER_FIX , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
