### ISSUE TITLE
[Module] ToyBox-Ext

### ISSUE THREAD

**Issue by zgfg** [Magisk-Modules-Alt-Repo/submission#54]
**Name**: ToyBox-Ext

**Description**:  Systemless Magisk module
to install (additional) ToyBox applets, using toybox ARMv7 and higher binaries from:
https://github.com/landley/toybox
SUPPORTED: ARMv7 and higher 

**Link**: https://github.com/zgfg/ToyBox-Ext

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/ToyBox-Ext, enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
