### ISSUE TITLE
[Module] 1Controller

### ISSUE THREAD

**Issue by Electric1447** [Magisk-Modules-Alt-Repo/submission#56]
**Name**: 1Controller
**Description**: Magisk module which adds proper key mapping for various game controllers.
**Link**: https://github.com/Electric1447/1Controller

**Comment by Atrate** [comment]
One thing before I can create a repo for you: `Module ID must match repo name (otherwise Magisk Manager fails to download it).`. You should either change the module ID to "1Controller" or I can create a repo named "OneController" for you, let me know which solution you'll take.

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/OneController, enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
