### ISSUE TITLE
[Module] Google_Product_Sans_Font

### ISSUE THREAD

**Issue by solomonrajan** [Magisk-Modules-Alt-Repo/submission#58]
**Name**: Google Product Sans Font for Android 12 and above
**Description**:  Systemless Google Product Sans Font for Android 12. A Magisk Mosule.
**Link**: https://github.com/solomonrajan/Google_Product_Sans_Font

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/Google_Product_Sans_Font , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your    feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
