### ISSUE TITLE
[Module] OverlayFS

### ISSUE THREAD

**Issue by HuskyDG** [Magisk-Modules-Alt-Repo/submission#59]
**Name**: OverlayFS
**Description**:  From Android 10+, system may no longer to be mounted as read-write. A simple script that can emulate read-write partition for read-only system partitions, make any modifications to system become systemless. OverlayFS is better than complex Magic Mount (see [Magic Mount vs OverlayFS](https://github.com/HuskyDG/magisk_overlayfs#magic-mount-vs-overlayfs)). Kernel must support and enable OverlayFS.
**Link**: https://github.com/HuskyDG/magisk_overlayfs

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/magisk_overlayfs, enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
