### ISSUE TITLE
[Module] Gaming Mode

### ISSUE THREAD

**Issue by imakira** [Magisk-Modules-Alt-Repo/submission#6]
**Name**: Gaming Mode
**Description**:  Gaming Mode that will get applied automatically when the game starts.
**Link**: https://github.com/imakira/Gaming-Mode
[Gaming-Mode_Module.zip](https://github.com/Magisk-Modules-Alt-Repo/submission/files/5165439/Gaming-Mode_Module.zip)

**Comment by tytydraco** [comment]
Hi! Good first submission. You need to put the contents of your module in the repo, specifically the master branch. Otherwise, Magisk Manager won't be able to download it.

**Comment by imakira** [comment]
Ok Thanks 👍

**Comment by imakira** [comment]
done

**Comment by tytydraco** [comment]
Module id must match repo name

**Comment by imakira** [comment]
Done btw i'm new here and thanks for help👍

**Comment by tytydraco** [comment]
https://github.com/Magisk-Modules-Alt-Repo/gamingmode
