### ISSUE TITLE
[Module] Flush RAM V1.7

### ISSUE THREAD

**Issue by Skrepysh** [Magisk-Modules-Alt-Repo/submission#60]
**Name**: Flush RAM V1.7
**Description**: Clear RAM apps caches, kill all apps, and force stop all apps to get more free RAM before playing games.
Use commands from Terminal Emulator
**Link**: https://drive.google.com/drive/folders/1-2LcL_aCG8W0SiuuomeHntc05Oo5lffm

**Comment by Atrate** [comment]
Your module needs to be a git repository, preferrably hosted on GitHub.

**Comment by spoxed** [comment]
Is there a way to add whitelist for apps like launchers or foregrounnd app to not be flushed?

**Comment by P-DhruviL** [comment]
Droping Apps Cached
Force Stopping 3rd Apps
Force Stopping Failure
cmd: Failure calling service activity: Failed transaction (2147483646)
Force Stopping calling
cmd: Failure calling service activity: Failed transaction (2147483646)
Force Stopping service
cmd: Failure calling service activity: Failed transaction (2147483646)
Force Stopping package
cmd: Failure calling service activity: Failed transaction (2147483646)
Flushing done
========================
