### ISSUE TITLE
[Module] MeMEUI Enhancer

### ISSUE THREAD

**Issue by snyfear** [Magisk-Modules-Alt-Repo/submission#62]
**Name**: MeMEUI Enhancer
**Description**:  Enhances MIUI for better battery backup and performance by tweaking core MIUI Services
**Link**: https://www.github.com/iamlooper/MemeUI-Enhancer

**Comment by Atrate** [comment]
Please provide the source code for all the executables in some way (such as on Github Wiki or in separate files). If these are just shell scripts compiled with shc, please just provide them as shell scripts instead of as compiled versions.

**Comment by Atrate** [comment]
Also, @snyfear, have you consulted with @iamlooper, the module author, before submitting this issue?

**Comment by snyfear** [comment]
No I didn't. I didn't even thought to it 😁

**Comment by Atrate** [comment]
See:
`The issue author must be the owner of the module being submitted, or have permission from the owner.`
