### ISSUE TITLE
[Module] DRC remover

### ISSUE THREAD

**Issue by yzyhk904** [Magisk-Modules-Alt-Repo/submission#63]
**Name**: DRC remover
**Description**:  A remover of DRC (Dynamic Range Control, i.e., a kind of compression) sticking to all audio outputs on some major devices.
**Link**: https://github.com/yzyhk904/drc-remover

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/drc-remover , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
