### ISSUE TITLE
[Module] Gboard user_dict_3_3 词库

### ISSUE THREAD

**Issue by entr0pia** [Magisk-Modules-Alt-Repo/submission#64]
**Name**: Gboard user_dict_3_3 词库
**Description**:  Magisk module of Gboard Dictionary, based on *Modern Chinese Dictionary*
**Link**: https://github.com/entr0pia/gboard_dict_3

**Comment by Atrate** [comment]
Please translate your README.md file to English (append a translated version to the end/beginning of the current file or move the Chinese version to a separate file). This is because Fox's MMM automatically grabs the README file to display module info.

**Comment by entr0pia** [comment]
Added translation.

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/gboard-dict-3, enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
