### ISSUE TITLE
[Module] TrichromeLibrary Squoosh

### ISSUE THREAD

**Issue by entr0pia** [Magisk-Modules-Alt-Repo/submission#67]
**Name**: TrichromeLibrary Squoosh
**Description**:  Remove the outdated TrichromeLibrary after reboot
**Link**: https://github.com/entr0pia/trichromelibrary-squoosh

**Comment by Atrate** [comment]
Please remove `customize.sh` and `system.prop` as they're completely empty except for some default comments. It would also be nice if you included a rationale as to why a user may want to remove the Trichrome library from their device. Other than that, looks good.

**Comment by entr0pia** [comment]
Remote unnecessary files ,and bold the rationale in the README.

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/trichromelibrary-squoosh, enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
