### ISSUE TITLE
[Module] NoStorageRestrict

### ISSUE THREAD

**Issue by DanGLES3** [Magisk-Modules-Alt-Repo/submission#68]
**Name**: NoStorageRestrict
**Description**:  Removes the restriction when selecting folders (Downloads/Android) through the file manager on Android 11 and higher
**Link**: https://github.com/DanGLES3/NoStorageRestrict

**Comment by Atrate** [comment]
Hey there, looks good! One thing, though; as noted in the Submission guidelines, `Module ID must match repo name (otherwise Magisk Manager fails to download it).`. Please change your module ID to NoStorageRestrict or let me know that you're fine with your repo being named `SkbA`.

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/NoStorageRestrict, enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
