### ISSUE TITLE
[Module] Zeetaa Tweaks Rebase

### ISSUE THREAD

**Issue by NotZeetaa** [Magisk-Modules-Alt-Repo/submission#69]
**Name**: Zeetaa-Tweaks-Rebase
**Description**:  Tweak your Kernel parameters. Check the github repo to get more info
**Link**: https://github.com/NotZeetaa/Zeetaa-Tweaks-Rebase

Can i request to remove old repo too? https://github.com/Magisk-Modules-Alt-Repo/Zeetaa-Tweaks
Ty

**Comment by Atrate** [comment]
Since your module id is `ZeetaaTweaks`, that's the repo name that will have to be created. I can delete the old repo and do that if you want.

**Comment by NotZeetaa** [comment]
> Since your module id is `ZeetaaTweaks`, that's the repo name that will have to be created. I can delete the old repo and do that if you want.

I will be grateful if you do that

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/ZeetaaTweaks , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.

**Comment by NotZeetaa** [comment]
Hey @Atrate sry for tag but is it fine change repo name? I changed it in my repo and i want to know if i can do it on Magisk Modules alt

**Comment by Atrate** [comment]
> Hey @Atrate sry for tag but is it fine change repo name? I changed it in my repo and i want to know if i can do it on Magisk Modules alt


As long as the module id and repo name stay the same, it should be good. Otherwise, it depends on how @Fox2Code 's app parses the modules now, it may have changed from before.

**Comment by NotZeetaa** [comment]
> > Hey @Atrate sry for tag but is it fine change repo name? I changed it in my repo and i want to know if i can do it on Magisk Modules alt
> 
> As long as the module id and repo name stay the same, it should be good. Otherwise, it depends on how @Fox2Code 's app parses the modules now, it may have changed from before.

I will change both
