### ISSUE TITLE
[Module] A12 Project Themer

### ISSUE THREAD

**Issue by Psk-Ita** [Magisk-Modules-Alt-Repo/submission#70]
**Name**: A12 QS PANEL MOD Universal
**Description**:  A12 Project Themer - free version
**Link**: https://github.com/Psk-Ita/Project-Themer

**Comment by Psk-Ita** [comment]
asking permission to plublish my module to the.developer
@Drsants0 does noto like my idea
Just delete.the request, sorry

**Comment by BNX070** [comment]
> **Name**: A12 QS PANEL MOD Universal **Description**: A12 Project Themer - free version **Link**: https://github.com/Psk-Ita/Project-Themer

Bro can you share the free version if possible?
