### ISSUE TITLE
[Module] Magic ToolFlash

### ISSUE THREAD

**Issue by HuskyDG** [Magisk-Modules-Alt-Repo/submission#71]
**Name**: Magic ToolFlash
**Description**:  A simple module that provide an android CLI flash tool without custom recoveries
**Link**: https://github.com/HuskyDG/magic-flashtool

**Comment by Atrate** [comment]
Looks mostly good, but please:
1. Format the code somehow (indenting etc.)
2. Replace all occurences of `$@` with `"$@"`, as the script will fail if a zip has spaces in its name.

**Comment by HuskyDG** [comment]
> Looks mostly good, but please:
> 
> 1. Format the code somehow (indenting etc.)
> 2. Replace all occurences of `$@` with `"$@"`, as the script will fail if a zip has spaces in its name.
> 3. Replace `$(which busybox)` with `"$(which busybox)"` for the same reason (if someone had a _very_ weird busybox location)
> 
> (You can use the `shellcheck` linux utility to check for possible errors in sh/bash scripts in the future)

Okey, 👍👍👍

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/magic-flash , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
