### ISSUE TITLE
[Module] Open Fonts

### ISSUE THREAD

**Issue by F3FFO** [Magisk-Modules-Alt-Repo/submission#73]
**Name**: Open Fonts
**Description**:  Magisk module to replace system fonts
**Link**: https://github.com/F3FFO/Open-Fonts

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/open_fonts , enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
