### ISSUE TITLE
DORA-ICONS

### ISSUE THREAD

**Issue by F5LAYD** [Magisk-Modules-Alt-Repo/submission#81]
**Name**: DORA-ICONS
**Description**:  Not a big module that adds new icons Dora Who is tired of looking at the old android icons I made my own they can like all the news I post in my telegram channel https://t.me/dora_icons Please sign and thanks in advance grinningheart😀❤️
**Link**: https://github.com/F5LAYD/DORA-ICONS

**Comment by F5LAYD** [comment]
Publish my module👍😀

**Comment by Atrate** [comment]
Please make sure your module conforms to how module repositories should be laid out. See https://github.com/Magisk-Modules-Alt-Repo/Magisk-DRM-Disabler for an example — you need to have the contents of the zip as your repo, not the zip itself.

**Comment by F5LAYD** [comment]
I don't know how to make it help me😀

**Comment by F5LAYD** [comment]
I do not know how to do it can you show how to do it?

ср, 27 апр. 2022 г., 10:31 Atrate ***@***.***>:

**Comment by Atrate** [comment]
See these resources for more information:
https://topjohnwu.github.io/Magisk/guides.html
https://arenaoftech.com/post/getting-started-with-magisk-modules/

**Comment by F5LAYD** [comment]
I read everything but nothing more useful is not found probably I will not be able to publish my module😭

**Comment by F5LAYD** [comment]
It is a pity that I could not please you 😖
