### ISSUE TITLE
[Module] CRV2/Stratosphere Performance Module

### ISSUE THREAD

**Issue by CRANKV2** [Magisk-Modules-Alt-Repo/submission#82]
**Name**: Stratosphere Performance Module

**Description**:  Tweak Module to improve you're experience and Power on your device.

**Link**: https://github.com/CRANKV2/CRV2

**Comment by Atrate** [comment]
Yeah, this is unacceptable. Obfuscating the source code of your scripts is not tolerable. All your scripts need to be fully readable. There are **several more striking issues** with your module, but you need to fix this first before we can proceed at all.
