### ISSUE TITLE
[Module] lhroot

### ISSUE THREAD

**Issue by FerryAr** [Magisk-Modules-Alt-Repo/submission#83]
**Name**: lhroot | Linux Chroot Installer
**Description**:  Systemless linux chroot installer and bootscript
**Link**: https://github.com/FerryAr/lhroot

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/lhroot, enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
