### ISSUE TITLE
[Module] ZeroLAG | By PietroVN (ME)

### ISSUE THREAD

**Issue by PietroVN-dev** [Magisk-Modules-Alt-Repo/submission#9]
**Name**: ZeroLAG
**Description**:  ZeroLAG is a module that focuses on releasing the maximum performance of your system, using tweaks from build.prop and modifying parameters in the kernel.
**Link**: http://www.github.com/PietroVN-dev/ZeroLAG

**Comment by tytydraco** [comment]
Hi! Glad to see your submission here ❤️ ❤️ 

I'm proud to see how you love to learn and improve. I'm glad you're dedicated! Enjoy the Alt-Repo.

https://github.com/Magisk-Modules-Alt-Repo/ZeroLAG

P.S.: Make sure to archive your repo on your personal account and use the Alt-Repo as your main repo. That way there are no discrepancies between versions. Enjoy!
