### ISSUE TITLE
OOS Native Call Recorder Enabler[Module]

### ISSUE THREAD

**Issue by doriandrey** [Magisk-Modules-Alt-Repo/submission#90]
**Name**: OOS Native Call Recorder Enabler Module
**Description**:  A simple module that does force native call recording OnePlus Oxygen OS.
**Link**: https://androidessentials.shadowstep.workers.dev/0:/OOS%20Native%20Call%20Recording/

**Comment by Atrate** [comment]
This seems no longer maintained. Have you consulted with @Zackptg5 before submitting this module?

**Comment by DerGoogler** [comment]
> This seems no longer maintained. Have you consulted with @Zackptg5 before submitting this module?

This looks dangerous https://github.com/Zackptg5/OOS-Native-Call-Recording-Enabler/blob/master/META-INF/com/google/android/update-binary

**Comment by Atrate** [comment]
Indeed,
