### ISSUE TITLE
[Module] SomcGameEnhancer-Upgrade

### ISSUE THREAD

**Issue by entr0pia** [Magisk-Modules-Alt-Repo/submission#91]
**Name**: SomcGameEnhancer Upgrade
**Description**:  Upgrade SomcGameEnhancer for Old Xperia Devices, Official Android 12 ROM only
**Link**: https://github.com/entr0pia/SomcGameEnhancer-Upgrade

**Comment by Atrate** [comment]
What's the source for the APK files?

**Comment by entr0pia** [comment]
I downloaded them from ApkMirror, they should be extracted from Xperia 1IV.

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/SomcGameEnhancer-Upgrade, enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
