### ISSUE TITLE
[Module] Magisk App Freezer

### ISSUE THREAD

**Issue by HuskyDG** [Magisk-Modules-Alt-Repo/submission#93]
**Name**: Magisk App Freezer
**Description**:  A simple module that automatically freeze magisk app if any app in DenyList is opened (except Google Play Store). Magisk app will get restored after closing all apps in DenyList.
**Link**: https://github.com/HuskyDG/magiskapp_freezer

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/magiskapp_freezer, enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.

**Comment by iqbalcyber** [comment]
please help me i my magisk wont be able to unhide again, how can i unhide manually without using pc, sorry for my bad english, hope you understand and give me a solution of my issue

**Comment by Atrate** [comment]
> please help me i my magisk wont be able to unhide again, how can i unhide manually without using pc, sorry for my bad english, hope you understand and give me a solution of my issue

You probably want to create an issue here: https://github.com/Magisk-Modules-Alt-Repo/magiskapp_freezer/issues
