### ISSUE TITLE
[Module] Basic Call Recorder (BCR)

### ISSUE THREAD

**Issue by YASHKRAJ** [Magisk-Modules-Alt-Repo/submission#94]
**Name**: Basic Call Recorder (BCR) Module

**Description**:  
BCR is a simple Android call recording app for rooted devices or devices running custom firmware. Once enabled, it stays out of the way and automatically records incoming and outgoing calls in the background.

**Link**: https://github.com/chenxiaolong/BCR/tree/v1.1

**Comment by Atrate** [comment]
Last guideline:
`The issue author must be the owner of the module being submitted, or have permission from the owner.`

Have you consulted with @chenxiaolong before making this submission?

**Comment by ashutossshhh** [comment]
can we record whatsapp call with this?
