### ISSUE TITLE
[Module] Audio jitter silencer

### ISSUE THREAD

**Issue by yzyhk904** [Magisk-Modules-Alt-Repo/submission#98]
**Name**: Audio jitter silencer
**Description**:  Disabling very large audio jitter generators (w.r.t. battery draining & optimizations, and wireless connectivity) for reducing audio jitter distortion on all digital audio outputs.
**Link**: https://github.com/yzyhk904/audio-jitter-silencer

**Comment by Atrate** [comment]
How do the outlined processes/services generate audio jitter?

**Comment by yzyhk904** [comment]
The amount of audio jitter can be defined as the standard deviation of actual audio data rate divided by its average data rate. For example, the expected average audio data rate of a 16bit 44.1kHz stereo track is 1.4112 Mbps (16 x 44.1 x 2 / 1000). If the standard deviation is 0.03 Mbps, then the jitter is 0.0212.

Assuming the adaptive mode (defined in the USB audio standard) is used between a host device and a USB DAC, and the PLL in this DAC attenuates the jitter down-to 1/10 times, then 1kHz sine test signal will have the standard deviation of 2.12 Hz. This is the audio jitter distortion caused by the variation of actual audio data rate.

Such outlined services having a high priority interfere the scheduling of a music app and wireless communication services and make the variation of actual audio data rate.

**Comment by Atrate** [comment]
Approved.

I have created a repository for you at: https://github.com/Magisk-Modules-Alt-Repo/audio-jitter-silencer, enjoy!

Check your e-mail inbox for an invite to your new repository and remember to 'Watch' your repository on Github to have new issues in it show up in your feed.

Make sure to change your local repository's push URLs or configure 2 parallel push URLs.
